### ISSUE TITLE
Implement LetsEncrypt

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/dbhub.io#10]
The main web based UI will need to use something other than a StartCom certificate.

LetsEncrypt (free) is used by a lot of places, and is probably a good choice instead.

**Comment by MKleusberg** [comment]
:+1: for LetsEncrypt :smiley:

**Comment by justinclift** [comment]
Making progress with this.  Our https://dev1.dbhub.io server is now using a manually created Lets Encrypt certificate.

It's possible to have the server code automatically grab a certificate when it starts up too, as this shows:  https://twitter.com/bitcurves/status/838531299082178560/photo/1

It doesn't look to complicated, so I'll try that approach next.

**Comment by justinclift** [comment]
That specific automated approach seems suitable for single server deployments only.

As we'll probably need to have servers behind a load balancer, it we'll need to look for a different approach.

Kind of thinking we'll need something that uses the "dns-01" challenge (as per the ACME protocol).

Lets Encrypt has supported that since [Jan 2016](https://twitter.com/letsencrypt/status/689919523164721152), so we'd just need to find a suitable client for running (eg from cron), which then stores the certs in ansible for deployment.

Some information on using certbot with DNS challenge here:

* https://community.letsencrypt.org/t/dns-based-challange-for-verification-of-letsencrypt-ssl-certs/28561

**Comment by justinclift** [comment]
This looks like what we want:

* https://serverfault.com/questions/750902/how-to-use-lets-encrypt-dns-challenge-validation
* https://github.com/lukas2511/dehydrated

**Comment by justinclift** [comment]
It's been pointed out that lists.sqlitebrowser.org and nightlies.sqlitebrowser.org are still using StartCom certs:

&nbsp; &nbsp; https://lists.sqlitebrowser.org/pipermail/db4s-dev/2017-April/000128.html

I'll get that fixed, probably later on today. :smile:

**Comment by justinclift** [comment]
The lists and nightlies servers have been updated to use Lets Encrypt certs now too.

**Comment by justinclift** [comment]
Closing this as we have Lets Encrypt already implemented, and it works when manually copying the generated cert to each of the nodes behind the load balancer.

The DNS challenge approach mentioned above will be useful, but not right now.
