### ISSUE TITLE
db4s: Return commit id after pushing database

### ISSUE THREAD

**Issue by MKleusberg** [sqlitebrowser/dbhub.io#100]
After having uploaded a new database or having pushed a new commit, it would be super-helpful to get the new commit id from the server 😄 Is it possible to add that (maybe in a small JSON document for future extensibility) to the POST request handler?

**Comment by justinclift** [comment]
Oh yep.  It's definitely possible to add that.  Presently, DB4S just sends back http status code 201 (Created), with a simple string "Database created: [db name]" in the body:

* https://github.com/sqlitebrowser/dbhub.io/blob/9dcc844c2bde028a8a4e578d4d9c526a1ac39010/db4s/main.go#L623-L625

It should be fairly simple to send a JSON response with useful info in the body instead.

Apart from commit id, does anything else spring to mind as being useful to include?  Note, it should be easy to add stuff later anyway if we're not sure yet. :smile:

**Comment by MKleusberg** [comment]
Hmm, the download URL of the database might be useful if that's possible to add. If not, I can generate that on the client side, too 😄

**Comment by justinclift** [comment]
No worries.  Should be pretty trivial to get done. :smile:

**Comment by justinclift** [comment]
Just pushed commit efd2a6ca4bab0f2c61547be64e65ccf516c4b306 which implements this.  Example of running curl against it:

```
$ curl -kE ~/my.cert.pem -D headers.out -F file=@a.db -F "public=true" -F "commitmsg=stuff" -F "sourceurl=https://example.org" -F "licence=CC0" -F "branch=master" https://db4s-beta.dbhub.io:5550/test1
{
  "commit_id": "409a042e6935e9d893b3bd793e16b8881095dfbe43e5f246833ae797152b7ead",
  "url": "https:/db4s-beta.dbhub.io:5550/test1/a.db?branch=master&commit=409a042e6935e9d893b3bd793e16b8881095dfbe43e5f246833ae797152b7ead"
}
```

Seem ok?

**Comment by MKleusberg** [comment]
Thanks! Looks good 😄 I'll test it some time later in DB4S, my local working dir is currently completely messed up by other stuff :wink:

**Comment by MKleusberg** [comment]
And finally I've tested this and it works as expected. DB4S now uses the returned commit id to directly update its database of locally checked out databases. With this we can avoid redownloading the database after each push :smile: Again, feel free to give it a try but I think we're safe to close this issue.

**Comment by justinclift** [comment]
Thanks @MKleusberg.  Will test soon, after getting food. :smile:

**Comment by MKleusberg** [comment]
Closing this because it's a very old issue and seems to be solved :smile:
