### ISSUE TITLE
DB4S: Include branch name in JSON listings

### ISSUE THREAD

**Issue by MKleusberg** [sqlitebrowser/dbhub.io#108]
Is it possible to include the branch name for each database in the JSON directory listings? Either in the URL (which already contains the commit id) or as a separate field? I understand that this is a bit redundant because we already have the commit id but I think I need this extra information to differentiate between different branches that are all locally checked out (which isn't possible yet) and to avoid errors when the default branch name changes (which can already happen).

**Comment by MKleusberg** [comment]
Looking at my code, including it in the URL would be ideal :wink:

**Comment by justinclift** [comment]
Yep, definitely do-able.  I'll get on that in a bit.  I've switched to my OSX desktop atm for testing the visual CSV preview string length thing, and to also try finding the crash when a key is pressed during the CSV import.

Once they're done though, I'll switch back to the Linux dev desktop (dbhub.io stuff is setup for it).

**Comment by justinclift** [comment]
@MKleusberg Is something like this ok?

```
[
  {
    "commit_id": "654bbeac93751cf93f1d0ddb2a7fe2dad2f8a28ab144b7726a780e0edd5a1cfd",
    "last_modified": "02 Oct 17 12:56 BST",
    "licence": "Not specified",
    "name": "a.db",
    "public": true,
    "sha256": "2305893384a11eb77b46c57022f9f76300dcc6c142618a83abb6a0b64805d790",
    "size": 20480,
    "type": "database",
    "url": "https://db4s-beta.dbhub.io:5550/justinclift/a.db?commit=654bbeac93751cf93f1d0ddb2a7fe2dad2f8a28ab144b7726a780e0edd5a1cfd&branch=master"
  }
]
```

Note the addition of the branch on the end of the `url` field. :smile:

**Comment by justinclift** [comment]
Just implemented that, and updated the db4s-beta server with it.  DB4S is still working when connecting to it, and uploading/download databases is still working, so it can't be too bad. :smile:

**Comment by MKleusberg** [comment]
Cool :smile: That's exactly what I wanted, will try it soon!

**Comment by MKleusberg** [comment]
Took me a while but DB4S is finally using this information now :wink:
