### ISSUE TITLE
Logging in with GitHub shows a 'testing' account

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/dbhub.io#130]
Logged in via GitHub account, and it shows it wants to connect to 'Testing 1' and 'Justin' (that part got cut off the screen capture, sorry...)

![image](https://user-images.githubusercontent.com/7872218/86234567-0a8dbd00-bb8f-11ea-8040-74d146dcf3b5.png)

Just wanted to check this was intentional.... still 'testing' ?

**Comment by justinclift** [comment]
Oh, that's interesting.  That's a test application I set up in our Auth0 account for doing development on.  It's not the "production" application.

I'll take a look at this in a bit.  Both should be set up identically, but still... that's not good.

And I'll probably need to create a **third** application just for testing purposes, now that we seem to have "real" logins going to both.  Gah. :facepalm:

**Comment by chrisjlocke** [comment]
Yes, I thought this was due to my creating loads of test accounts when we were playing around with logging in, but when I click the 'log in with GitHub', its the next screen that appears - there isn't a 'enter your GitHub credentials' thing, so unsure if its a cookie thing its getting or not, but I'll try clearing everything and having another go.  It had the right avatar, so it knew I was logged in...

**Comment by justinclift** [comment]
Looking into this more now, it's the Auth0 configuration on the DBHub.io server side is using the "correct" account. **\*whew\***

Further investigation shows that's really a "GitHub OAuth App" that I set up for this ages ago and completely forgot about.  Just renamed it, and also uploaded our general logo to it.

Hopefully if you try again, it looks ok now? :smile:

**Comment by chrisjlocke** [comment]
I've tried clearing cookies, but I don't get the Auth login page now, as I assume I've been auth'd ?  
Aah, just seen I can delete the entry.

![image](https://user-images.githubusercontent.com/7872218/86253615-af6ac300-bbac-11ea-978a-e487d6ad79c8.png)

Is 'Auth0' a default name?  Should it be 'dbhub.io' ?

Talking of Auth0 and logos, this is the first login page I see...

![image](https://user-images.githubusercontent.com/7872218/86253772-e0e38e80-bbac-11ea-9e8c-d09bf373178b.png)

So still logo-less?

**Comment by justinclift** [comment]
Yeah, there's two different pieces.  The GitHub OAuth App we can change the logo for.  And you're right, the name should be "DBHub.io" instead of ""Auth0".  Just updated that now. :wink:

**Comment by justinclift** [comment]
@chrisjlocke Is this resolved? :smile:

**Comment by chrisjlocke** [comment]
Still says 'Auth0' and the default logo when I go to log in...

![image](https://user-images.githubusercontent.com/7872218/87014064-7b525c00-c1c3-11ea-845c-8a8c6d296834.png)

The other part (buried in github) is OK

![image](https://user-images.githubusercontent.com/7872218/87014361-f156c300-c1c3-11ea-99fc-042d7ad7e11f.png)

When you click that though, it takes you to a 'profile' page for dbhub.io, which seems to have a weird 'go here' link

![image](https://user-images.githubusercontent.com/7872218/87014419-07fd1a00-c1c4-11ea-8fb6-d2d92e74488f.png)

(dbhub.eu.auth0.com).  When you click that, it does just redirect you to auth0.com, rather than dbhub.io - don't know if that can be changed anywhere?  Or even if anyone is going to care.... 😉

**Comment by justinclift** [comment]
> Still says 'Auth0' and the default logo when I go to log in...

Yeah, that doesn't seem to be changeable.  At least, not in the Auth0 UI pieces I've seen. :shrug:

The "dbhub.eu.auth0.com" piece is correct in a way too, as we have an EU account with them.  Not sure why they're showing it there though.

**Comment by chrisjlocke** [comment]
No problem.  Thanks for fixing the other bits!

**Comment by justinclift** [comment]
No worries.  Really glad you pointed out the problem(s) so they could be fixed. :smile:
