### ISSUE TITLE
[Suggestion] More prominent link to raise an issue

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/dbhub.io#131]
Went to leave an issue here, and on the main page, its kind of hidden.  There is a link at the bottom, 'Get Involved' and then 'GitHub' but another of 'Support' and 'Create a support issue' link (pointing to the 'new issue' link?) could be useful...

**Comment by justinclift** [comment]
Good thinking.  That should be super easy to add.  I'll get that done after getting some food. :smile:

**Comment by justinclift** [comment]
Just updated the site page footer to include a support link (409e5b61ee8786ea38dd94da520c7387a9510b2b).

Does it look ok to you?

&nbsp; &nbsp; https://dbhub.io

**Comment by chrisjlocke** [comment]
Excellent, thanks!  A quick 'n easy way for people to raise questions is good.  
Aah, on the 'communication' is worth adding a Wiki link?  (https://github.com/sqlitebrowser/dbhub.io/wiki)
Really must install Git so I can create a PR! 😉

**Comment by justinclift** [comment]
> Really must install Git so I can create a PR!

Actually yeah.  Please do that. :smile:

**Comment by justinclift** [comment]
> Aah, on the 'communication' is worth adding a Wiki link? (https://github.com/sqlitebrowser/dbhub.io/wiki)

Probably a good idea.  Make a PR? :grin:

**Comment by justinclift** [comment]
@chrisjlocke ping? :wink:

**Comment by chrisjlocke** [comment]
![image](https://user-images.githubusercontent.com/7872218/86615791-da8a5380-bfac-11ea-9c17-8b500fccc591.png)

(That's my 'oops, its on my list' face! 😉 )

On the plus side, I did actually get around to installing Git Desktop...

**Comment by justinclift** [comment]
> I did actually get around to installing Git Desktop...

Baby steps.  As long as you get there... :smile:

**Comment by justinclift** [comment]
Closing this, as the link was added. :smile:
