### ISSUE TITLE
webui: Database settings has no menu

### ISSUE THREAD

**Issue by MKleusberg** [sqlitebrowser/dbhub.io#133]
When looking at a database I have uploaded and navigating through the menu items (Data, Visualise, Discussions, Merge Requests, Settings) I just noticed that this is missing on the Settings page. The entire page looks a bit different and the only way to go back is by using the Back button of the browser.

Same for Commits, Branches, Tags, Releases, and Contributors.

**Comment by justinclift** [comment]
Errr... screenshot?

**Comment by justinclift** [comment]
Oh.  I get what you mean.  Yeah, the settings page uses a completely different base template/layout.

I suppose it could be switched over to use the same layout as the other ones. :smile:

**Comment by MKleusberg** [comment]
Data:
![Screenshot_20200710_103525](https://user-images.githubusercontent.com/3153504/87134652-41538980-c299-11ea-8fd8-5556641b53a9.png)

Visualise:
![Screenshot_20200710_103553](https://user-images.githubusercontent.com/3153504/87134671-47496a80-c299-11ea-9e00-595ebcd0f40d.png)

Settings:
![Screenshot_20200710_103605](https://user-images.githubusercontent.com/3153504/87134680-4adcf180-c299-11ea-91b4-8b879a59a7b6.png)

**Comment by MKleusberg** [comment]
Just fixed this :smile:

**Comment by justinclift** [comment]
Awesome! :smile:
