### ISSUE TITLE
Tailing a View for changes via golang API

### ISSUE THREAD

**Issue by joe-getcouragenow** [sqlitebrowser/dbhub.io#135]
Not sure if this is already possible but could not find it from a quick look.

Basically It would be really useful to get a change event back out to the golang API when a row change event occurs on a View or Table. 

In terms of who it tells of the change i think that a webhook is the simplest way. I tend to use NATS for those sort of things that are asynchronous also, but i am guessing most people would prefer something agnostic like a web hook.
I guess the webhook could hold a base64 description of what changed.

Also TIDB does this, in case your curious. Here is an example of how it updates Kafka of all DB changes:
https://github.com/pingcap/ticdc/tree/master/kafka_consumer

This whole area is called CDC ( Change Data Capture). Took me a while to realise this is the Pattern 👍

**Comment by justinclift** [comment]
Thanks @joe-getcouragenow, that sounds like a useful suggestion. :smile:

At the moment (!) our [Go API](https://github.com/sqlitebrowser/go-dbhub) is effectively Read Only, as the backend storage version control's everything.  eg when someone runs a query (or whatever) on a database, it needs to a be a SELECT query, and it runs on the latest revision of the database.

We're adding an Upload function to the API (likely later on today), but that'll just add a new revision of a database.  Queries still need to be Read Only.

We could think of how to wire up a change event on uploads, but it doesn't sound anywhere near as granular as your suggestion.  Your suggestion seems more like the kind of thing useful for live (eg read/write) databases, which aren't on version controlled storage?

Personally, I've been thinking we should add support for live databases. but haven't really thought through how we'd potentially implement it.  It'd need a different storage backend (possible, maybe not too hard), and we'd have to figure out a useful initial approach for contention issues.

Along those lines, what the scenario you'd be thinking of using the Go API in?  It could be good input for us figuring out an initial approach. :smile:

**Comment by justinclift** [comment]
@joe-getcouragenow FYI, there's a minor typo on the [GCN FAQ page](https://www.getcouragenow.org/faqs):

```
Unfortunately you can’t fo this on IOS.
```

"fo" → "do"

**Comment by justinclift** [comment]
@joe-getcouragenow FYI, there's a minor typo on the [GCN FAQ page](https://www.getcouragenow.org/faqs):

```
Unfortunately you can’t fo this on IOS.
```

"fo" → "do" :wink:

**Comment by joe-getcouragenow** [comment]
Ah had no idea that this does not support live databases.

thanks for FAQ typo :)
will close...
