### ISSUE TITLE
question - online access

### ISSUE THREAD

**Issue by livadask** [sqlitebrowser/dbhub.io#140]
Hi,

Can I have an online Sqlite database accessed by mobile apps ?

**Comment by chrisjlocke** [comment]
Via an API (so in an app) yes.
At the moment, databases are read only (select statements only supported).

**Comment by justinclift** [comment]
@livadask As @chrisjlocke mentions, yes but only "read only" for now.  So, no `INSERT`, `UPDATE`, and `DELETE` statements aren't yet supported.

If that's of interest, check out https://dbhub.io. :smile:

**Comment by justinclift** [comment]
Closing this, as it seems to be answered.
