### ISSUE TITLE
Basic send/receive of SQLite databases from DB4S (SQLite Browser)

### ISSUE THREAD

**Issue by BataBoom** [sqlitebrowser/dbhub.io#142]
Is this available? My Database is constantly getting updated and I'd like a way to communicate with it outside.

**Comment by justinclift** [comment]
It's a bit unclear if you're asking whether you can save/retrieve databases using DB4S, or via API call from your own application.

That being said, both work.  DB4S itself has a "Remote" tab where you can save and retrieve databases.  The same databases can be grabbed using the [DBHub.io API](https://api.dbhub.io).

Is that what you're asking about? :smile:

**Comment by BataBoom** [comment]
Thanks for the speedy reply and apologies for the lack of mine. 

![image](https://user-images.githubusercontent.com/56499256/108951510-5a8d2880-7625-11eb-8f9d-d4a73cba331d.png)

Is this the only location to configure remote? I don't  really understand it, just says that I can clone the DB onto my local system again or I reckon import a cert to the Hub Service for magic API. The API might be a solution, I try to hide from json but it always finds me. 

Thanks!

**Comment by chrisjlocke** [comment]
OK, I've just done a 'tutorial' video.  Give me a bit of time to edit the needful.  But in a 'quick guide', go to dbhub.io, create an account, set your name (or DB4S moans later), grab a certificate, load that into DB4S, and you're done.
I'll upload a video here shortly, or yell back if you need something more urgent, and I'll spot it... 👍

**Comment by chrisjlocke** [comment]
Wow - that took longer than I thought.  First real attempt at this, so yell back if anything doesn't make sense or you want me to expand on anything.  There will be more of these, as this just tickles the iceberg.  

https://streamable.com/qfnu80

**Comment by BataBoom** [comment]
Nice voice AI not even lying, its far from annoying like most! xP 

Appreciate the effort youve gone above and beyond. If this were a couple years(s) ago id offer to donate some crypto but potentially I've made bad choices and havent got much left. All I can say is, Love you =]

**Comment by chrisjlocke** [comment]
Haha!  I personally found it a bit annoying (but maybe because I was listening to her all morning!) and found the drop in pitch in every sentence repetitive ... but that was my fault for doing short sentences ("click that.  Now click that.") but hey - better than me doing it!

Hopefully we'll be able to get these out though, as they're useful.  Hope it showed you what to do.  Yell back what isn't clear, so I can make the next one better! ☺

**Comment by justinclift** [comment]
Closing this, as it seems all taken care of. :smile:
