### ISSUE TITLE
Remotely executing SQLite queries with Python

### ISSUE THREAD

**Issue by LeMoussel** [sqlitebrowser/dbhub.io#147]
Ref: [New API for remotely executing SQLite queries](https://sqlitebrowser.org/blog/new-api-for-remotely-executing-sqlite-queries/)

**Using Python for this example:**
```
import requests
import base64

# dbhub.io Api key
API_KEY = 'YOUR_API_KEY_HERE'
# The owner of the database to query
DB_OWNER = 'justinclift'
# The name of the database
DB_NAME = 'Join Testing.sqlite'

sql = '''
SELECT table1.Name, table2.value
FROM table1 JOIN table2
USING (id)
ORDER BY table1.id;
'''
base64_sql = base64.b64encode(sql.encode('ascii'))

files = {
    'apikey': (None, API_KEY),
    'dbowner': (None, DB_OWNER),
    'dbname': (None, DB_NAME),
    'sql': (None, base64_sql),
}

response = requests.post('https://api.dbhub.io/v1/query', files=files)
data = response.json()

print(data)
```

**Comment by chrisjlocke** [comment]
Is this issue simply an example of you getting it working, or is something not working?

**Comment by LeMoussel** [comment]
This issue is simply an example to the community.

**Comment by chrisjlocke** [comment]
Fantastic, thanks for sharing!  Appreciated!

**Comment by LeMoussel** [comment]
Do you think it would be interesting to have a Python library for accessing and using SQLite databases stored remotely on [DBHub.io](https://dbhub.io/) (like [go-dbhub](https://github.com/sqlitebrowser/go-dbhub))?

**Comment by justinclift** [comment]
Yes, definitely!  If you want to create some kind of Python library for people to use, then **please** go ahead. :smile:

**Comment by LeMoussel** [comment]
OK. I'm looking to make a Python library. 
Don't be surprised to see API requests with the User Agent: `pybhub v1.0.0`. That's me :)

**Comment by justinclift** [comment]
> Don't be surprised to see API requests with the User Agent: pydbhub v1.0.0. That's me :)

Awesome! :smile:
