### ISSUE TITLE
Probable security risk on db4s.dbhub.io

### ISSUE THREAD

**Issue by LeMoussel** [sqlitebrowser/dbhub.io#148]
With Firefox, I got a warning about a possible security risk on the SSL certificate of [db4s.dbhub.io](https://db4s.dbhub.io/).

[SSL Checker](https://www.sslshopper.com/ssl-checker.html#hostname=https://db4s.dbhub.io/)
> - The  certificate is not trusted in all web browsers. You may need to install  an Intermediate/chain certificate to link it to a trusted root  certificate. Learn more about this error. The fastest way to fix this problem is to contact your SSL provider.
> - This certificate will expire in 2 days. Renew now.

[Wormly ](https://www.wormly.com/test_ssl/h/db4s.dbhub.io/i/161.35.206.89/p/443)
> - Expires in 2 days. Certificate will expire soon
> - Not trusted. The certificate was issued by DBHub.io DEVELOPMENT Intermediate CA, which is not a trusted authority. This is most likely because the servers' certificate chain is not installed correctly

**Comment by chrisjlocke** [comment]
Yes, the certificate expires soon, similarly to the certificates in DB4S, which will be updated soon and a new version of DB4S released.
As for the other 'errors' .... oooooooh. 😊
Thanks for letting us know.

**Comment by MKleusberg** [comment]
The other errors are kind of to be expected as we are using a self signed certificate. So browsers and utilities like SSL Checker will throw errors but that's fine for us as you'll mostly be using DB4S and dio to communicate with db4s.dbhub.io and those are shipped with the correct certificates built-in.

That said, we should definitely renew the certificates and ship a new version of DB4S and dio. @justinclift Anything I can do to help with that?

**Comment by justinclift** [comment]
> Anything I can do to help with that?

I'm generating new certs and stuff atm.  Should have new release binaries ready for signing in a couple of hours... :wink:

**Comment by justinclift** [comment]
Closing this, as I forgot to close it after updating the certs. :wink:
