### ISSUE TITLE
Insert new record using query method

### ISSUE THREAD

**Issue by hhaydar** [sqlitebrowser/dbhub.io#149]
is it possible to insert new record on tables?...

curl -F apikey="API_KEY" -F dbowner="jdoe" -F dbname="mydata_file" -F sql="SU5TRVJUIElOVE8gc29uZ" https://api.dbhub.io/v1/q

Error:

error": "not authorized (INSERT INTO song_list VALUES('DkDjEr3opt0',0,'','')) (authorization denied)"

Note:

sql decode: INSERT INTO table VALUES('A',0);

**Comment by justinclift** [comment]
At the moment, no. :frowning: Uploaded databases are read-only.

So, to add new info, you need to do it to a local copy (eg using DB Browser for SQLite), then upload the new version.

That being said, yeah it's a huge pain in the butt for a lot of use cases.  So, we'll need to figure out a way to make this work properly for people.  It won't be in the next few days, but may be possible in a few weeks. :smile:

**Comment by hhaydar** [comment]
Thank you Justin,
