### ISSUE TITLE
Error with Diff API function

### ISSUE THREAD

**Issue by LeMoussel** [sqlitebrowser/dbhub.io#150]
Like describe in [Diff Api function documentation](https://api.dbhub.io/#diff), I do this CURL Request:

`curl -F apikey="MY_API_KEY" -F dbowner_a="justinclift" -F dbname_a="Join Testing.sqlite" -F commit_a="cb70855613d30019055a4d907b832c10014b093556fc282e6b7d2803e2e9d59" -F commit_b="218f28dcb54819e7e4b77e36012ff15d667ca55946c56ef6370b13bdc3ddf528" -F merge="preserve_pk" https://api.dbhub.io/v1/diff`

I got this error:
```
{
  "error": "Key: '' Error:Field validation for '' failed on the 'min' tag"
}
```

I don't understand this mistake. 

But If I do this CURL Request with `DB4S download stats.sqlite` and other  commits, I got some results.

`curl -F apikey=""MY_API_KEY"" -F dbowner_a="justinclift" -F dbname_a="DB4S download stats.sqlite" -F commit_a="34cbeebfc347a09406707f4220cd40f60778692523d2e7d227ccd92f4125c9ea" -F commit_b="bc6a07955811d86db79e9b4f7fdc3cb2360d40da793066510d792588a8bf8de2" -F merge="preserve_pk" https://api.dbhub.io/v1/diff`

**Comment by justinclift** [comment]
Interesting.  Good find @LeMoussel!

@MKleusberg Any ideas? :smile:

**Comment by MKleusberg** [comment]
The validation the the value in ```commit_a``` fails because it's one character to short. In general both commit ids don't seem to match the database. So this isn't really a (major) bug but we should definitely fix the error message for these cases.

**Comment by LeMoussel** [comment]
OK.
Note that the example in the documentation for the Diff function is incorrect.

**Comment by MKleusberg** [comment]
Fair point :wink: I've just updated the example in the documentation to fix that.
