### ISSUE TITLE
Can't make a new discussion

### ISSUE THREAD

**Issue by jungle-boogie** [sqlitebrowser/dbhub.io#151]
Hi,

I'm trying to make a new discussion on my database repo, but clicking create doesn't do anything. I've disabled `ublock` and still cannot post.

If the database is public, can anyone start a new discussion? If so, see if you can create one:

https://dbhub.io/creatediscuss/jungle-boogie/LasVegasMetroTraffic.db

Thanks!

**Comment by justinclift** [comment]
@chrisjlocke Do you have time to try this out?  I'm heading off to work atm, and won't be back for 12+ hours.

**Comment by jungle-boogie** [comment]
By the way, I don't see any errors in Firefox's network console, either.

**Comment by chrisjlocke** [comment]
Creating a merge request worked, with no errors shown.

![image](https://user-images.githubusercontent.com/7872218/117614891-e280ca00-b160-11eb-93aa-448ffaa29414.png)

**Comment by chrisjlocke** [comment]
Just tried on my work PC (Still Edge ... think the previous test was actually in Firefox) and get a slightly different error - but in the same file (client.js)

![image](https://user-images.githubusercontent.com/7872218/117669344-b126ef00-b19e-11eb-9475-c9189ca00484.png)

**Comment by justinclift** [comment]
Yeah, spotted that.  No idea yet where that problem is coming from.

I don't personally have time to investigate tonight though... and with the way the new job is going, it may be a weekend thing. :angel:

**Comment by MKleusberg** [comment]
It's an issue on our side. The submit button tag is not inside the form node. I'll try to fix it :smile:

**Comment by MKleusberg** [comment]
It's fixed now :smile: Thank you for pointing this out, @jungle-boogie! https://dbhub.io/discuss/jungle-boogie/LasVegasMetroTraffic.db?id=1
