### ISSUE TITLE
Can't view schema change

### ISSUE THREAD

**Issue by jungle-boogie** [sqlitebrowser/dbhub.io#152]
Hi,

I updated a view in my schema. I can see the message in dbhub that there was a schema change, but there is no way to view the change.

https://dbhub.io/diffs/jungle-boogie/LasVegasMetroTraffic.db?commit_a=172eecdd40a38d8457fe7fb74f29e7b468c1dae48b58314c1ea8293755bd18c0&commit_b=ad2e054d5941b30db828137d506fba5923a1192d81b26e5f7ad9db0211d4660d

Notice there's "view" text, but it's not a link and nothing pertaining to it looks like it a link.

How can we see the schema modifications?

Thanks!

**Comment by jungle-boogie** [comment]
Happened with this commit as well:

https://dbhub.io/diffs/jungle-boogie/LasVegasMetroTraffic.db?commit_a=0188755cf8076fe067259295641e4b12500142a73e435bf8eb896e9ed069fc31&commit_b=dd9666145fc3192862e0b4ba4734a042e95b212e5df4ea2a2bdcc79cff41a3a8

**Comment by justinclift** [comment]
Interesting.  @MKleusberg ? :smile:

**Comment by MKleusberg** [comment]
Thanks, @jungle-boogie! I have just fixed this. It now shows the previous and the current CREATE statements. This should be enough to figure out what changed in most situations :smile:
