### ISSUE TITLE
[Info] Python library for accessing and using SQLite databases stored remotely on DBHub.io

### ISSUE THREAD

**Issue by LeMoussel** [sqlitebrowser/dbhub.io#154]
Hi!

As indicated in issue [#147](https://github.com/sqlitebrowser/dbhub.io/issues/147#issuecomment-830757713), I have developed a Python library for accessing and using SQLite databases stored remotely on [DBHub.io](https://dbhub.io/) (like [go-dbhub](https://github.com/sqlitebrowser/go-dbhub)).

You can see it on  [LeMoussel / pydbhub](https://github.com/LeMoussel/pydbhub)

**Comment by chrisjlocke** [comment]
Thanks for taking the time to make and post this!

**Comment by justinclift** [comment]
Awesome, that looks like a really good start @LeMoussel. :smile:

Going to add it to PyPi?

Btw, on the README.md for it, there's a text fragment: `Older Python releases should NOY be OK`  Is that `NOY` a typo?

**Comment by justinclift** [comment]
Oh, related to this, I've started working on improving on the API backend code again.  It's just early stage Work-In-Progress stuff as I get time to each night, but we **should** have the ability to set permissions for each API key via the user settings page soon (this wkend?).

There will likely be other stuff we want to add/fix/change/etc, but I think that'll be a useful next step. :smile:

**Comment by LeMoussel** [comment]
> Btw, in the README.md for it, there's a text fragment: `Older Python releases should NOY be OK` Is that `NOY` a typo?

Trivial typo. Fixed.

> Going to add it to PyPi?

Yes it's planned.

>  I've started working on improving on the API backend code again. 

OK. Keep me informed when it is operational. (Rem: I'm watching all notifications from  [sqlitebrowser/go-dbhub](https://github.com/sqlitebrowser/go-dbhub) repository)

**Comment by justinclift** [comment]
Cool. :smile:

Will add a link to pydbhub from the API page in a bit.  As a data point, if you have thoughts/ideas/etc on ways we can improve the API so it's more useful to people, they're welcome. :smile:

**Comment by justinclift** [comment]
Added a link to it, from the ["Libraries" section of the api front page](https://api.dbhub.io/#libraries).  Hopefully that helps increase usable of the library, and of the DBHub.io api. :smile:

**Comment by justinclift** [comment]
* Also added a link from the DBHub.io repo front page, as that seems like a good place too.
* And [tweeted](https://twitter.com/sqlitebrowser/status/1401066833763987460) about it too.

Probably should write a blog post to announce it as well, while we're at it... :smile:

**Comment by justinclift** [comment]
Just added a blog post as well: https://sqlitebrowser.org/blog/first-release-pydbhub/

Ok, that's about all I can think of for letting people know / promoting it, etc. :smile:

**Comment by LeMoussel** [comment]
Available on PyPi.
View at: https://pypi.org/project/pydbhub/0.0.2/

**Comment by justinclift** [comment]
Awesome!

Just updated the blog post about it, the link from the api.dhub.io page, and added info about that on Twitter too. :smile:

**Comment by justinclift** [comment]
Oops, accidentally left this open.  Closing this now. :smile:
