### ISSUE TITLE
Create a new commit to existing database error 

### ISSUE THREAD

**Issue by Xmonpl** [sqlitebrowser/dbhub.io#158]
Hello, I try to create a new commit to the existing database but unfortunately, a received this error. Does someone help me?

Error: 
```java
403
{
  "error": "A database with that name already exists.  Please choose a different name or clone the existing database first."
}
```

Code:
```java
    public CompletableFuture<String> upload(@NonNull File location, @NonNull String branch, @NonNull String commit_name) throws Exception {
        if (asyncHttpClient != null) {
            final List<Part> parts = List.of(
                    new StringPart("apikey", this.apikey),
                    new StringPart("dbname", "test_db"),
                    new StringPart("branch", branch),
                    new StringPart("force", "true"),
                    new StringPart("public", "false"),
                    new StringPart("commitmsg", "Example from api"),
                    new StringPart("lastmodified", new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssXXX").format(location.lastModified())),
                    new FilePart("file", location, "application/x-sqlite3", StandardCharsets.UTF_8)
            );
            return asyncHttpClient
                    .prepareGet("https://api.dbhub.io/v1/upload")
                    .addHeader("Content-Type", "multipart/form-data")
                    .setBodyParts(parts)
                    .execute()
                    .toCompletableFuture()
                    .thenApply(x -> {
                        System.out.println(x.getStatusCode());
                        return x.getResponseBody();
                    });
        } else {
            throw new Exception("Database Connection isn't open");
        }
    }
```

**Comment by justinclift** [comment]
Ahhh, interesting.  It looks like the request being sent to add the new commit, isn't including the info of the existing commit to append to.

Give me a few minutes to poke through the source code of the server, as it shouldn't be too hard to work out what it's wanting...

**Comment by justinclift** [comment]
This looks to be the initial mention at the top of the upload function (in the code): https://github.com/sqlitebrowser/dbhub.io/blob/bf7e9a41af955fbf9262098d1273fd207ddf2a35/api/handlers.go#L664-L666

Interestingly, the [api docs page](https://api.dbhub.io/#upload) says it's `commit_id`.  Looks like a mismatch there... checking the server code itself now...

**Comment by justinclift** [comment]
The field name it's checking for is `commit`: https://github.com/sqlitebrowser/dbhub.io/blob/bf7e9a41af955fbf9262098d1273fd207ddf2a35/common/userinput.go#L133

So, the api doc page needs updating to say that instead of `commit_id`.  :facepalm:

I'll get that done now. :wink:

Meanwhile, is that enough info for you to get past the problem you were having @Xmonpl?

**Comment by justinclift** [comment]
k, that's been fixed and deployed.

If it doesn't work for you for some reason @Xmonpl, please let us know so we can investigate. :smile:

**Comment by Xmonpl** [comment]
Yes, everything works now. Thank you very much for your help <3

**Comment by justinclift** [comment]
Awesome. :smile:
