### ISSUE TITLE
FTS5

### ISSUE THREAD

**Issue by jadsongmatos** [sqlitebrowser/dbhub.io#160]
is it possible to use FTS5 feature?

**Comment by justinclift** [comment]
That's a good idea.  The FTS5 extension hasn't been added to the SQLite version we're using, but it should be possible to add.

It'll probably be next week or weekend though, not in the next few days.

**Comment by justinclift** [comment]
It's only a few years overdue (!), but progress is now being made with this.

The same extensions we use in the DB Browser for SQLite nightly builds, are now available for use our Live databases.  They are:

  * COLUMN_METADATA
  * FTS3
  * FTS3_PARENTHESIS
  * FTS5
  * GEOPOLY
  * JSON1
  * MATH_FUNCTIONS
  * RTREE
  * SOUNDEX
  * STAT4

For reference, the commit which added them is: https://github.com/sqlitebrowser/dbhub.io/commit/d1f469cd37d5ee8c817fec09c285951d8cc15ac8

**Comment by justinclift** [comment]
This has been deployed to production, and is available for both Standard and Live databases.

As Standard databases are read only, they'll need the FTS5 added before being uploaded.  FTS5 queries will operate fine on them after they're uploaded though.

For Live databases, the FTS5 virtual tables and data can be created any of the standard ways to run SQL.  eg via the API, via the `Execute SQL` tab, uploaded after creation in DB4S, etc.
