### ISSUE TITLE
Improve Repo Main Page - Latest Commit

### ISSUE THREAD

**Issue by hl2guide** [sqlitebrowser/dbhub.io#162]
Please consider improving the main repo page by adding to the right top section, e.g:

`Visibility: Public   Commit: ##########  Latest Commit: 13 hours ago  Licence: CC-BY-SA-4.0   Size: 100 KB`

(Addition is "Latest Commit: 13 hours ago")

**Comment by justinclift** [comment]
Good idea, that definitely makes sense.  Should be able to do it pretty simply too.  eg this weekend :smile:

**Comment by justinclift** [comment]
@hl2guide Sorry it took a while longer than expected.  Thanks to @MKleusberg, it's been implemented and is live now. :smile:
