### ISSUE TITLE
dbhub.io internal certificate expired

### ISSUE THREAD

**Issue by Lightning-** [sqlitebrowser/dbhub.io#168]
seems that some internal cert of dbhub.io expired.  
trying to push a change using db4s gives this error:  
```Error transferring https://db4s.dbhub.io/Lightning/sithrev.sqlite - server replied: Internal Server Error
Get "https://db1.dbhub.io:9000/5193b1/?location=": x509: certificate has expired or is not yet valid: current time 2022-06-27T22:15:09Z is after 2022-06-25T07:51:29Z```

**Comment by chrisjlocke** [comment]
> using db4s

What version of DB4S are you using, and on what OS?
The internal certs did expire, but the latest version of DB4S should be good to go...

**Comment by justinclift** [comment]
@Lightning- Thanks for pointing this out @Lightning-.  You're right, that's a cert for one of the internal database servers.

I knew the certificate was going to expire, however I disregarded it as the database software isn't bothered about certificate expiry times.

But I'd forgotten we also have another piece of software running on the same server.  :facepalm:

I've just renewed it's certificate, and restarted the affected component, you're good to go now.

Sorry for this hassle, we won't be making *that* mistake again. :angel:

**Comment by Lightning-** [comment]
running v3.12.1 on (slackware) linux.  
the ca certs from the certmanager are valid until 2027 (intermediate) and 2037 (root).  
i'm not trying to run anonymously but upload to my account with my own client cert (which is valid till march 2023), so i never took care about v3.12.2. this message is not about the certs from https://github.com/sqlitebrowser/sqlitebrowser/commit/d85953c291b5f0bb467e2c12dfa4438f997d4f28 which already expired 2021.  
my last working commit was on 2022-06-23, so this is something new :)  
as `db1.dbhub.io` doesn't resolve to anything publicly, i guess this is a somehow forwarded error message that gets piped through some sort of backend.

**Comment by justinclift** [comment]
Yeah, this is definitely an internal component thing.  Try it again now? :smile:

**Comment by Lightning-** [comment]
works like a charm, thx =D
