### ISSUE TITLE
Question - Usage limitations

### ISSUE THREAD

**Issue by silvioprog** [sqlitebrowser/dbhub.io#170]
Hi.

I am going to develop an open source command-line application for handling personal expenses/finances. It will use a SQLite database and allow the users to backup their data in an online storage.

So, can I use the service DBHub.io and the library [go-dbhub](https://github.com/sqlitebrowser/go-dbhub) for such purpose?

TIA for any help!

**Comment by chrisjlocke** [comment]
Currently there are no limits.  This may be revised if an explosion in demand occurs, but for the moment .... code away! ;)
Good luck with it.

**Comment by silvioprog** [comment]
Thanks a lot for clarifying! :-)
