### ISSUE TITLE
license "info" link opens in a new tab

### ISSUE THREAD

**Issue by wibeasley** [sqlitebrowser/dbhub.io#171]
I'm enjoying exploring this site.  Here's a tiny suggestion.

A few minutes ago I was choosing a license.  When I clicked the "Info" link next to "CC0",  it opened in the same tab, instead of a new tab.  I had to re-enter a small amount of info (the public/private and the license).  Consider showing that license info in a new tab.

![image](https://user-images.githubusercontent.com/1372890/186990940-c2d2c4cc-c221-42ff-ac69-f2ba29ad1666.png)

**Comment by chrisjlocke** [comment]
Good point.  A quick fix.  Looks doable.
Thanks for reporting it!

**Comment by MKleusberg** [comment]
Well, this took a bit longer than it should have. But it's finally fixed. The new code will be deployed on our servers soon. Waiting for @justinclift here.

**Comment by justinclift** [comment]
This update was deployed a few days ago, so clicking on these license info links should no longer mean accidentally losing any data in the current tab. :smile:
