### ISSUE TITLE
How to delete an API key ？

### ISSUE THREAD

**Issue by cktime** [sqlitebrowser/dbhub.io#172]
## How can I delete an API key when I don't want to use it, I can't find the delete button in the web interface
![图片](https://user-images.githubusercontent.com/93019859/187058871-5f11123a-44cb-4bc7-a303-5776dda781eb.png)

**Comment by chrisjlocke** [comment]
Don't think you can yet.  It's OK - as we don't charge you rent for it, you can just ignore any you don't use. :)
