### ISSUE TITLE
Consider renaming default branch to main

### ISSUE THREAD

**Issue by blakegearin** [sqlitebrowser/dbhub.io#174]
Update default branch name from `master` to `main` to match major platforms.

- GitHub: https://github.com/github/renaming
- GitLab: https://about.gitlab.com/blog/2021/03/10/new-git-default-branch-name/
- Bitbucket: https://bitbucket.org/blog/moving-away-from-master-as-the-default-name-for-branches-in-git

Here are some places that would need updating:

https://github.com/sqlitebrowser/dbhub.io/blob/9172af969bcab17fc8af9a8308d24603f7cd1aeb/common/responses.go#L377-L380

https://github.com/sqlitebrowser/dbhub.io/blob/b1c7351acab673abe2041e4544e75614802d0104/api/templates/root.html#L168-L181

**Comment by MKleusberg** [comment]
I tend to agree making this change. It would be consistent with Git as well as (in my opinion) being a better description for the purpose of this branch.

@justinclift Any opinion? I could make that change then.

**Comment by justinclift** [comment]
Go for it if you want. :smile:

**Comment by MKleusberg** [comment]
The default name is changed to "main" in all components of the tool. I'll wait for @justinclift though to activate the new code on the server.

**Comment by justinclift** [comment]
Cool.  I'll try it out in a test setup in the next few days, just to verify things are indeed working fine with the change.

@MKleusberg We should probably think about setting up GitHub Actions (or similar) for this repo, using the Cypress tests.  There are still a few pages that need work (eg Discussions, Merge Requests), but the core pages should all be covered already.

**Comment by justinclift** [comment]
@MKleusberg Just stumbled over what seems to be a bug in the profile page (on latest `master`), when no test databases have been loaded into the `default` test users's profile:

```
2023/02/21 08:24:58 Error: template: profile.html:197:18: executing "profilePage" at <.SharedWithYou>:
  can't evaluate field SharedWithYou in type struct { Auth0 common.Auth0Set; Meta common.MetaInfo;
  PrivateDBs []common.DBInfo; PublicDBs []common.DBInfo; Stars []common.DBEntry; Watching []common.DBEntry }
```

I'm not mentally awake enough atm to fix it, but if you're interested then it's there.  Otherwise I'll get to it when I'm feeling better. :smile:

**Comment by MKleusberg** [comment]
The default branch name has been changed to "main" and the new code is active on the server. Existing branch names are not changed though. I'll close this issue then :smile:
