### ISSUE TITLE
'Internal Server Error' when uploading database

### ISSUE THREAD

**Issue by Lightning-** [sqlitebrowser/dbhub.io#176]
i'm currently not able to upload/update my database (with sqlitebrowser); server breaks somehow with messages like:
`Error transferring https://db4s.dbhub.io/Lightning/sithrev.sqlite - server replied: Internal Server Error
open /home/dbhub/.dbhub/disk_cache/dbhub-upload-3713431191: no such file or directory`

think there's some disk-issue here ;)

**Comment by Lightning-** [comment]
`DB Browser for SQLite Version 3.12.1` on linux (i really gotta compile 3.12.2 somewhen :joy:)

**Comment by chrisjlocke** [comment]
That might help.
Good news - it appears to be working for other people.

drwxr-x--- 2 dbhub dbhub         3 Feb  5 15:15 
drwxr-x--- 2 dbhub dbhub         3 Feb  5 15:22 
drwxr-x--- 2 dbhub dbhub         3 Feb  5 15:41 
drwxr-x--- 2 dbhub dbhub         3 Feb  5 16:13 
drwxr-x--- 2 dbhub dbhub         3 Feb  5 16:16 
drwxr-x--- 2 dbhub dbhub         3 Feb  5 16:17 
drwxr-x--- 2 dbhub dbhub         3 Feb  5 16:19 

So its doing _something_.  
I tried the latest commit from master and that worked OK (albeit on Kubuntu) so ... er ... hopefully its something in the older version thats a bit pants?

**Comment by chrisjlocke** [comment]
> on linux

What distro are you using? (just so we can possibly test and confirm)

**Comment by Lightning-** [comment]
slackware current (somehow, need some updates but don't think this harms anything).
last successful push i did was 2023-01-23 11:23; didn't change anything since then (and even got the same db4s instance running)

**Comment by chrisjlocke** [comment]
v3.12.1 is one release behind (we're on 3.12.2) and even that is mega old compared to master (or main).

**Comment by Lightning-** [comment]
yeah, i know it's one release behind. according to the changelog i never found the need to upgrade for this minor change. but if you think that's the issue, i can do the jump of course. release or rather main/master?

**Comment by justinclift** [comment]
Interesting.  As Chris mentioned, we recently changed/updated the part of the infrastructure that DB4S connects too.  It *could* be that, though it also might be something else.

Looking now. :smile:

**Comment by justinclift** [comment]
Just found and fixed a simple thing (missing cache dir on filesystem) that _might_ explain the problem.

@Lightning- If you try again now, does it work?

**Comment by Lightning-** [comment]
works like a charm :smiley:

**Comment by justinclift** [comment]
Awesome!  When we setup the new (bigger/faster/etc) server for DB4S to connect to, we tested by *downloading* some databases.

Looks like we should have uploaded some databases as well, as that would caught this problem at the time.

Well, we know for next time.

Thanks heaps for letting us know. :smile:

**Comment by justinclift** [comment]
As a data point, @chrisjlocke just added a check for this problem in the server startup code: b164c35611da2e1019742c3e9f442ecaca2bf40d

Shouldn't ever happen again.  In theory. :wink:
