### ISSUE TITLE
Is dbhub.io still active/sustained?

### ISSUE THREAD

**Issue by penyuan** [sqlitebrowser/dbhub.io#178]
I recently discovered dbhub.io and am loving the concept. Also super glad that the whole stack is fully open source under the AGPLv3. Many thanks for creating it!

I see, however, that there's only one blog post in 2022 and the Twitter account hasn't been active since 2021.

Therefore, before jumping in, I just want to see if dbhub.io is still actively sustained and that I can (relatively) safely start using without fear that it will be gone in two weeks? 😄

**Comment by justinclift** [comment]
Yeah, it's actively developed.  Things went a bit quiet (development wise) during Covid, though the infrastructure running everything was maintained throughout.

Development has starting picking up again a few weeks ago (after the new year), and is expected to continue for the foreseeable future. :smile:

**Comment by justinclift** [comment]
> there's only one blog post in 2022 and the Twitter account hasn't been active since 2021.

Yeah.  We really should do more blog posts.  I've personally been meaning to, but we'll see how it goes.

Twitter though, meh.  Twitter is kind of a dumpster fire, so it's probably not going to get much activity in future either.

**Comment by penyuan** [comment]
> > there's only one blog post in 2022 and the Twitter account hasn't been active since 2021.
> 
> Yeah. We really should do more blog posts. I've personally been meaning to, but we'll see how it goes.

Looking forward to more posts with updates on the project. 🤗

> Twitter though, meh. Twitter is kind of a dumpster fire, so it's probably not going to get much activity in future either.

Yeah, I am also not a fan of Twitter, was just using to figure out if there's any activity at all.

Thanks for sustaining the development of dbhub.io and keeping the whole thing fully open source!

**Comment by justinclift** [comment]
No worries. :smile:

As a general thought with git projects, a useful way to get an idea of activity is to cast your eye over their "commit history".  eg:

https://github.com/sqlitebrowser/dbhub.io/commits/master

*Most* of the time that's a reasonably reliable way to see what's going on.  That being said, some projects (not us) organise themselves a bit differently, which can result in activity not showing up properly there.

**Comment by fadhly-permata** [comment]
@penyuan Its so active, few days ago I am opening an [issue](https://github.com/sqlitebrowser/dbhub.io/issues/178), and been [solved](https://github.com/sqlitebrowser/dbhub.io/commit/0b272ef9fbbadd11b3141fa5f5f847e8bfbfea5f) ASAP by @justinclift

**Comment by justinclift** [comment]
@penyuan We've started doing blog posts again too: https://sqlitebrowser.org/blog/ :smile:

**Comment by justinclift** [comment]
Hmmm, I'm going to close this as it seems pretty clear this project is still active/sustained. :smile:
