### ISSUE TITLE
Different styles for 'Star' button depending on current state

### ISSUE THREAD

**Issue by MKleusberg** [sqlitebrowser/dbhub.io#18]
Just one minor but easy to fix thing: when viewing a database you get the 'Stars: 0' button at the top and clicking the button increases the value to 'Stars: 1'. Clicking it again unstars the databases and toggles the button back to 'Stars: 0'. So far so good. But other than the number increasing or decreasing I get now feedback whether I've starred the current database or not. I suggest doing it Github style and changing the button caption to 'Unstar: 1' plus changing the style of the button somehow additionally.

**Comment by justinclift** [comment]
Good thought.  Shouldn't be too hard to implement. :smile:

**Comment by justinclift** [comment]
Gah, accidentally closed due to commit message text.

**Comment by justinclift** [comment]
@MKleusberg In theory, this should be working ok now.  Do you have time to test it out on dev to confirm? :smile:

**Comment by MKleusberg** [comment]
Seems to work fine :)
