### ISSUE TITLE
[Question] Are views supported?

### ISSUE THREAD

**Issue by rasa** [sqlitebrowser/dbhub.io#181]
Even though the field says "Table/view:"
<img width="92" alt="2023-03-18_10-49-06-chrome-DBHub io_-_rasa__default db_-_Google_Chrome" src="https://user-images.githubusercontent.com/220772/226124424-f3486e34-2898-4126-99c2-f74836d8d886.png">

Are views supported?

When I download the uploaded database, the views are still there when I view the downloaded .db locally.

**Comment by justinclift** [comment]
@rasa Yes, they're supposed to be.

If you find a view doesn't work in something, please let us know (in detail) so we can track that piece of code down and find out what's going on.  Then fix it. :smile:

**Comment by rasa** [comment]
The views are listed after the tables. I foolishly thought the list would be alphabetical, as it is in the DB Browser for SQLite's "Browse Data" tab. Sorry for the noise.

**Comment by justinclift** [comment]
Ahhh.  That's a good point.  I was looking over the code for that yesterday while working on other stuff.  Pretty sure that "views are listed after the tables" is because I just appended the view list to the table list without thinking about it further.

It should be pretty simple to put them into a single sorted list.  Will take a look shortly. :smile:

**Comment by justinclift** [comment]
Yep, this is the code responsible:

https://github.com/sqlitebrowser/dbhub.io/blob/d0849c8dc033d102bd456fc443988b76cef2f6d8/common/sqlite.go#L936-L937

Having that be a sorted list instead is straight forward.  I've just made the change in my local development setup, and it's running through the test suite now.  When that passes (assuming no weird edge cases show up), I'll roll it out to our production systems.

**Comment by justinclift** [comment]
k, that change is live on our production system.  Try now. :smile:
