### ISSUE TITLE
Remove folders

### ISSUE THREAD

**Issue by MKleusberg** [sqlitebrowser/dbhub.io#183]
I would like to remove the concept of folders from the source code. Right now it just increases the number of parameters of functions a lot (and there are too many already) and adds extra complexity without even being implemented. So removing it would simplify the code without losing any functionality. You could argue that folders could be added later and removing the existing code now makes this a lot more difficult later but in my opinion this argument is wrong for multiple reasons:

1. Folders are not used in all the places right now either. So adding them later would require review of the entire code anyway.
2. This concept of folders would be very limited anyway as it would support only one level of directories. With multiple levels (maybe separated by forward slashes) this concept would be very prone to errors and hard to implement. If we ever decide to go this route we should replace any references to a database by a database ID or so instead of using owner + folder + name.
3. I think folder names in URLs are problematic. One thing is that they make validation awkward, the other is that renaming a folder invalidates any number of database links. Again, using an ID in these cases might be the better approach.

So I think we can safely remove folders without even losing anything in the future. Thoughts? Another question would be whether to keep the column in the database and keep in the SQL queries so we can reuse it later as a reference to some other database table which describes directory structures.

**Comment by justinclift** [comment]
Yeah, go for it.  They're just placeholders most of the time anyway. :smile:

**Comment by justinclift** [comment]
> Another question would be whether to keep the column in the database and keep in the SQL queries ...

Up to you.  Probably want to try doing this piecemeal at first, as there are a fair number of SQL queries that'll need updating. :smile:

eg, maybe start with nuking the `dbFolder` parameter from all function calls.  When that's taken care of, maybe then do the PG backend SQL?

But, it's up to you so do whatever works. :smile:
