### ISSUE TITLE
Guest Database File (SQLite)

### ISSUE THREAD

**Issue by aamirjk2000** [sqlitebrowser/dbhub.io#186]
Share Guest Database file

**Comment by justinclift** [comment]
Hi @aamirjk2000,

That's a bit unclear.  I'm *guessing* you want to share a private database with someone?

If that's the case, it's fairly simple:

1. Make sure both people have an account on DBHub.io
2. Upload the database you want to share.  Select the `Standard` database type, not the `Live` database type
3. In the "Settings" page for the database, there is a section for `Share Database`.
   *. In this section, there is a field to type in the username you want to share with.  Type in their username, then click the `+` button next to it, then click the `Save` button further down the page.

That *should* work.  If it doesn't, or if you were asking about something else... just let us know. :smile:

**Comment by justinclift** [comment]
@aamirjk2000 Did that help at all?

**Comment by justinclift** [comment]
Closing this, due to lack of response.  If you do need assistance, please feel free to re-open this or create another issue, preferably with more detail. :smile:
