### ISSUE TITLE
Fossil SCM hosting would be awesome!

### ISSUE THREAD

**Issue by bobhairgrove** [sqlitebrowser/dbhub.io#191]
Are there any plans for hosting Fossil remote repositories on DBHub.io?

Since you are already hosting SQLite databases, it seems only logical that you might also put Fossil support into the mix.

**Comment by justinclift** [comment]
I've not really looked at Fossil, though I'm aware of it.

Any idea what it would take?

**Comment by justinclift** [comment]
Looking over the Fossil code [here](https://fossil-scm.org/home/dir?ci=trunk), it seems to be C based and needs to run it's own server.

Pretty much all the server software on DBHub.io is written in Go, because it's easy to reason with, stable (as languages go), and (*almost totally*) avoids lots of memory safety issues.  C doesn't.  Well, C as a language probably is pretty stable, but that's about it.

I guess the answer is "Fossil hosting is unlikely in the short or medium term", as it's not really the direction the project is going in. :smile:

**Comment by bobhairgrove** [comment]
> Looking over the Fossil code [here](https://fossil-scm.org/home/dir?ci=trunk), it seems to be C based and needs to run it's own server.

Although Fossil CAN run as a (local) server with its built-in server software, it doesn't HAVE to:

https://fossil-scm.org/home/doc/trunk/www/server/

The easiest way (IMHO) would be to run it as a CGI script. Fossil is built as a stand-alone executable and only needs to be callable by the user running the CGI script.

> Pretty much all the server software on DBHub.io is written in Go, because it's easy to reason with, stable (as languages go), and (_almost totally_) avoids lots of memory safety issues. C doesn't. Well, C as a language probably is pretty stable, but that's about it.
> 
> I guess the answer is "Fossil hosting is unlikely in the short or medium term", as it's not really the direction the project is going in. smile

**Comment by chrisjlocke** [comment]
On that note, I did see https://chiselapp.com/ which does Fossil SCM hosting.

DBHub.io just takes the raw sqlite database.  I guess it wouldn't take much to work out if a database is a Fossil repository or not* .. but it would be a bucketful of code to maintain.

*Fossil is just a SQLite database based repository of files .. ala Git.

**Comment by justinclift** [comment]
> The easiest way (IMHO) would be to run it as a CGI script. Fossil is built as a stand-alone executable and only needs to be callable by the user running the CGI script.

Again, that's effectively running it as a server.  eg Fossil's code gets executed in response to incoming requests over a network.

Whether there's a reverse proxy, CGI gateway, or other alternative mechanism in place in front of it, it's still executing potentially memory unsafe code on the backend in response to network requests.

While that in itself isn't a complete show stopper, we'd need to implement some proper production grade containerization approach to handle that scenario, to be on the safe side.

It'd probably also need to be one-container-per-user (that's using Fossil), which is going to be expensive memory wise.

For now, we're better off keeping focused on improving our core offering (hosting SQLite databases).  Though when that's all running super well and we're in a position to consider other stuff, this *might* be a good thing to investigate again.

**Comment by justinclift** [comment]
> Sadly, that host seems to be rather dormant these days.

Ouch.  Yeah, looking over that Chiselapp place, it looks pretty dead. :frowning_face:
