### ISSUE TITLE
[Suggestion] Remove size from download database link

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/dbhub.io#197]
![image](https://user-images.githubusercontent.com/7872218/235353858-0690018a-9aba-4fab-b936-9fce7b70d8c0.png)

Just doing a screenshot for the 'download database' feature, and noticed the link has a database size.  However, just above the link is the size for the database.
This seems duplication of information.  Admittedly I assume the value in the download link could be more 'up to date' (if they upload a load of data between the page load and downloading the database) and at least confirms the size, but from a 'data overview', it does add to the noise.
Maybe.

**Comment by justinclift** [comment]
Ahhh good point.  I can update that right away.  Gimme 5 mins. :smile:

**Comment by justinclift** [comment]
k, the fix is live in production now too.
