### ISSUE TITLE
no issue

### ISSUE THREAD

**Issue by Njorogej46** [sqlitebrowser/dbhub.io#20]
great work guys thanks this is a godsend

**Comment by justinclift** [comment]
Heh Heh Heh, you're welcome. :smile:

Just out of curiosity, are you meaning the SQLite GUI or the server side part?

Asking because the GUI itself works reasonably well, but the server side part is still in it's early stages.  Basic stuff is still missing.  We are improving that though. :wink:

**Comment by justinclift** [comment]
Closing this, as it's not really something we need to "do anything" with. :smile:
