### ISSUE TITLE
[Webpage] Database query failed error encountered

### ISSUE THREAD

**Issue by junosg** [sqlitebrowser/dbhub.io#204]
Hi, encountered this error on login and on navigation to home page of Dbhub.io web page.

![image](https://github.com/sqlitebrowser/dbhub.io/assets/76584438/613fff11-b483-4d1d-823c-8aba41eb5266)

I tried registering a new account and the new account don't have this error. Will I be able to recover my databases on my previous account? Thank you.

**Comment by chrisjlocke** [comment]
Thanks for reporting.  It seems to have logged you in - are things working past this point?  If you log out and back in, do you get the same error?  Does your username contain unicode characters?

**Comment by junosg** [comment]
Hello, logging out and back in displays the same error.  No, my username does not contain a unicode character. For reference, my username is "junosg".

Not sure if this will help but here is the console log.
![image](https://github.com/sqlitebrowser/dbhub.io/assets/76584438/a67c52f7-0f76-4e75-b500-8597f60b81ee)

Thank you.

**Comment by junosg** [comment]
Hello, tried logging in today and this is resolved on my end.

![image](https://github.com/sqlitebrowser/dbhub.io/assets/76584438/1d351e94-066c-4536-b2c4-e7ff52dfa4c3)

Thank you.
