### ISSUE TITLE
How to change password or delete account?

### ISSUE THREAD

**Issue by jwhetzel-gpc** [sqlitebrowser/dbhub.io#209]
Hi!  I would like to be able to change my account password, or if there is no way to do that, then delete my account.  I looked around the preferences page and couldn't find anything that would get me there.  Thanks!

**Comment by chrisjlocke** [comment]
How did you sign up?  Using your github account, google, linkedIn or an email and password?

![image](https://github.com/sqlitebrowser/dbhub.io/assets/7872218/19f66403-b588-4ce0-b5a2-eeac0c4ec8ee)

**Comment by jwhetzel-gpc** [comment]
It was email and password.

**Comment by justinclift** [comment]
@jwhetzel-gpc Apologies for the delay, I somehow completely missed several issues that have been created in this repo. :facepalm:

@chrisjlocke We should be able to manage the "email & password" logins through the Auth0 web interface.  I'll take a look at this tomorrow some time, as we should be able to help @jwhetzel-gpc to change their password, delete their account, etc, from there.

**Comment by chrisjlocke** [comment]
> through the Auth0 web interface

Aah, didn't even know there was a web interface!

**Comment by chrisjlocke** [comment]
Can you let me know your email address used for signup (or username).  If you can email me at issue209 at chrisjlocke.co.uk rather than post it here.  Thanks!

**Comment by jwhetzel-gpc** [comment]
> Can you let me know your email address used for signup (or username). If you can email me at issue209 at chrisjlocke.co.uk rather than post it here. Thanks! Sorry for the delay in replying to this!

Thanks, Chris!  Email sent.

**Comment by justinclift** [comment]
@chrisjlocke Reminder ping. :smile:

**Comment by chrisjlocke** [comment]
Account deleted as requested.
