### ISSUE TITLE
Unable to download DB Browser for SQLite for Mac (Intel)

### ISSUE THREAD

**Issue by vicambulist** [sqlitebrowser/dbhub.io#214]
Good day,

I'm trying to download DB Browser for SQLite for Mac (Intel) at the following link:
https://download.sqlitebrowser.org/DB.Browser.for.SQLite-3.12.2.dmg

I am unable to download the file. Is something wrong with the server?

Thank you!
Bret

**Comment by chrisjlocke** [comment]
Thanks for reporting.  The DB Browser for SQLite issue area is at https://github.com/sqlitebrowser/sqlitebrowser/issues
I've given the server a swift kick, and seems it was sulking about something.
Please try again. :)

**Comment by chrisjlocke** [comment]
Closed as resolved.
