### ISSUE TITLE
Support for RTL languages

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/dbhub.io#22]
We'll probably need to add support for RTL languages in the database view page.

For example, according to translate.google.com the text here is Arabic, which (from memory) should be displayed from right to left:
![screen shot 2017-04-09 at 13 59 23](https://cloud.githubusercontent.com/assets/406299/24837472/f330c502-1d2c-11e7-908b-d970e01369a7.png)

**Comment by MKleusberg** [comment]
@justinclift Can you test the commit I've just pushed. *In theory* this should work on most modern browsers. :smiley:

**Comment by justinclift** [comment]
Oh wow, that would be excellent.  Yep, I'll test it in about an hour. :smile:

Thanks heaps @MKleusberg. 😁

**Comment by justinclift** [comment]
Excellent, that worked! :smile:

I'll update the dev1 server now.

**Comment by MKleusberg** [comment]
Cool, one thing less to worry about :smiley:
