### ISSUE TITLE
API calls on live databases stopped working

### ISSUE THREAD

**Issue by neyl66** [sqlitebrowser/dbhub.io#226]
Hello!

Since couple of days ago, API calls on live databases seem to have stopped working.

Responses are with status 500 and error message i got:
```json
{
	"error": "Exception (504) Reason: \"channel/connection is not open\""
}
```

**Comment by justinclift** [comment]
Oh damn, thanks for pointing this out.

We need to add some backend code to make job scheduling more robust, and until that's in place (few weeks away) things might be a bit flaky. :facepalm:

That being said, we have some monitoring in place for a similar problem to this one, so might be able to adapt that in the short term to restart any services that exhibit this problem.

Will look into that over the weekend most likely, to see if that's workable.

**Comment by neyl66** [comment]
Can confirm it now works again, thanks for the quick fix!

**Comment by justinclift** [comment]
Re-opening this for now, until the updated reconnection code is in place. :smile:

**Comment by justinclift** [comment]
@neyl66 As a data point, the piece of code/infrastructure that was causing the underlying problem has been swapped over to a new system.

Things should be much more robust now.  In theory. :pray:

**Comment by justinclift** [comment]
On a different topic, I've just noticed this:

https://github.com/neyl66/node-dbhub

Should that be added to the Libraries list at the top of the https://api.dbhub.io page? :smile:
