### ISSUE TITLE
impossible to add an user in Share Database

### ISSUE THREAD

**Issue by jborderon13** [sqlitebrowser/dbhub.io#227]
Hello,

I would like to add an user in settings/share databse to allow someone to modify the db but when I click on the + button after I write a username nothing happens. I tried with chrome and firefox. Do you know why ? 
Thanks !

**Comment by jborderon13** [comment]
It works for me but not for anyone else, same as you...

**Comment by jborderon13** [comment]
My bad, thanks for your time, everthing works perfectly.

**Comment by chrisjlocke** [comment]
Thanks for confirming.  What was the problem - user didn't exist?
Ideally, it would be helpful if we said, 'user not found' but I think that's done for security .. although its obvious it hasn't worked .. so I'll check. :)
