### ISSUE TITLE
Add "commit messages"?

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/dbhub.io#26]
With git, each commit has an optional commit message.

Should we add similar for versions?  eg when a new version is uploaded, ask the user for an optional commit message

We'd need to display it appropriately on the database version list page (still to be written).

As a first thought, I'm kind of thinking it's a reasonable idea

**Comment by chrisjlocke** [comment]
I'm sure it has its uses.  Nothing worse than looking at a database
thinking, "why did I upload that??"

**Comment by MKleusberg** [comment]
Yep, sounds like a good idea. Especially when working in a team and merging databases etc.

**Comment by justinclift** [comment]
Cool.  I'll add a "Commit message" field to the database upload page.

Any suggestions for a better phrase than "Commit message"?  Kind of thinking that phrase might be a bit weird for people not familiar with git itself, so something a bit more generic might be better.

**Comment by justinclift** [comment]
Closing this, as commit messages were implemented in the new data model.
