### ISSUE TITLE
Per version license info

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/dbhub.io#27]
Just realised we'll probably need to have the license information be "per version" instead of "per database".

For example, lets say someone publishes 10 versions of a data set over time using licenseA.

If they change the license to licenseB for the 11th version, that needs to be just for that one specific version (onwards) and not suddenly be applied to all previous versions.

Probably a good thing I haven't written much of the license handling code yet, although it's pretty close to getting focused on now.

**Comment by MKleusberg** [comment]
I probably wouldn't bother implementing a per version license information. it's not just harder to implement for us and harder to comprehend for users but also quite difficult to do right. When the license changes this could mean that all data is relicensed entirely, i.e. only the new license is used; it could mean that it's dual licensed from that version on; it could mean that only the newly added data from that version on is under the new license while the old data is still using the former license; it could be a combination of the last two; or it could mean that only the data added in this particular commit uses the new license and every change before and after uses a new license, e.g. when importing a foreign data set. The point is that there are so many possible combinations and use cases that it's going to be hard to please them all. So it's probably just easier for everyone to have a big text box where the users can explain their license model individually. What do you think? :smiley:

**Comment by justinclift** [comment]
Ahhh, interesting points.  I'd been planning on having a catch all "Other" field anyway 😀 , but it sounds like we should probably discuss it with potential users.

I'll start a discussion about this on the OKFN forums, asking for thoughts (etc), and see if there's a clear direction they'd recommend. :smile:

**Comment by justinclift** [comment]
Closing this as an initial (hopefully :wink:) working licence implementation was added in 2b65b1bc7ca382a506efd73e9fa108253e88737b.  I'm not 100% happy with the way that implementation displays the licence info in the settings page... but it's probably good enough to start with for getting people using it and giving constructive feedback. :smile:
