### ISSUE TITLE
Find a solution to the display problem with very wide tables

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/dbhub.io#35]
At the moment, if a table has many fields then the table data display of it goes very wide in our webUI. eg:
![screen shot 2017-05-01 at 13 01 15](https://cloud.githubusercontent.com/assets/406299/25579292/74a0aee8-2e6e-11e7-881f-92c24fe2a46f.png)

We should probably figure out a way to have that width contained, perhaps using the same approach Gitea uses:
![screen shot 2017-05-01 at 13 14 29](https://cloud.githubusercontent.com/assets/406299/25579485/39de4502-2e70-11e7-991c-d63f15a1474b.png)
![screen shot 2017-05-01 at 13 15 01](https://cloud.githubusercontent.com/assets/406299/25579486/3e15fc8c-2e70-11e7-8963-d2dd7402670e.png)
![screen shot 2017-05-01 at 13 15 05](https://cloud.githubusercontent.com/assets/406299/25579488/41ca8780-2e70-11e7-8794-49ae613d6685.png)
Not sure how they're doing that, but it seems to be something about table cell style attributes.  If we put our data display table inside another table (a single cell), we might be able to acheive the same effect.

**Comment by MKleusberg** [comment]
See here: https://jsfiddle.net/Wcgvt/181/ (not my code). There you can see how to add scrollbars in vertical direction but it's exactly the same for horizontal direction. In line 30 of the CSS code you define the height (or width for our case) of the inner div, and the ```overflow: auto;``` in line 27 of the CSS adds the scrollbars to the outer div.

**Comment by justinclift** [comment]
Awesome!  I'll give that a go over the next few days. 😄

**Comment by justinclift** [comment]
Finally got around to this with a69ad911e834c8a970230fac0745c1afa9af395c.  A horizontal scroll bar is now shown for overly wide tables, and seems reasonable.

At the least, it's a lot better than it was. :smile:

**Comment by iKlsR** [comment]
That's the thing with these patches/fixups, they hinder getting real stuff done. I would suggest moving to a framework that has this stuff built in already. ie. responsive tables instead of the inline css which is manageable now because of size but will be troublesome later on.

**Comment by justinclift** [comment]
Well.. the inline CSS all over the place is pretty much because I'm just keeping the first thing I manage to get working.  Some major refactoring would clean up a lot of stuff, though yeah... not completely eliminate the problem. 😀
