### ISSUE TITLE
Problems SSL CA cerficate

### ISSUE THREAD

**Issue by MItchPisa76** [sqlitebrowser/dbhub.io#383]
HI,
Since this morning it's seem that the SSL cerficate was expired, I try to create a new one but every call to web API "https://api.dbhub.io/v1/query" results in a:
- Curl error 60: Cert verify failed. Certificate has expired. UnityTls error code: 7
- SSL CA certificate error:

From the web access:
"This server failed to prove that it is dbhub.io. The protection certificate expired yesterday. The problem could be caused by a misconfiguration or an attacker intercepting the connection. The computer clock is currently set to Sunday, November 3, 2024. If necessary, correct your system clock settings and refresh this page."

Yesterday all works fine
Any help?

Thanks

Mitchpisa

**Comment by justinclift** [comment]
Oops.  Looks like I forgot to renew the https certificate.  On it now...

**Comment by MItchPisa76** [comment]
> Oops. Looks like I forgot to renew the https certificate. On it now...

Ok thanks!

**Comment by justinclift** [comment]
Thanks for the heads u @MItchPisa76, it's fixed now.

I've been working through the process of automating the certificate renewals, but missed the dbhub.io ones and some of the sqlitebrowser.org ones.  Ugh.

If you noticed any other certificate weirdness, please let us know as they should all be good now. :smile:
