### ISSUE TITLE
Error opening remote file at https://db4s.dbhub.io/.  The certificate has expired

### ISSUE THREAD

**Issue by ZkrAbbd690** [sqlitebrowser/dbhub.io#386]
Error opening remote file at https://db4s.dbhub.io/.  The certificate has expired:

**Comment by ZkrAbbd690** [comment]
this is an error I get after trying to connect to DBHub.io with public identity ???

**Comment by justinclift** [comment]
@ZkrAbbd690 Oops.  I'll check it later on today when I get to the co-working space.

**Comment by justinclift** [comment]
Didn't get to it today, it'll have to be tomorrow morning. :frowning:
