### ISSUE TITLE
Unable to access remote database via DB4S

### ISSUE THREAD

**Issue by tomhosker** [sqlitebrowser/dbhub.io#388]
1. Tried to access my database (dbhub.io/tomhosker/hgmj.db) today via DB4S, the same way I've been doing for the past year.
2. Got a message saying that my certificate was out of date.
3. Downloaded a new certificate, added it via the menu in DB4S, but still the same message saying my certificate was out of date.
4. Reinstalled DB4S to latest snap version. Added my new certificate again.
5. Now I get a different error message: "Host db4s.dbhub.io not found".

Any idea where I'm going wrong?

**Comment by justinclift** [comment]
Sorry @tomhosker, that certificate error is my fault.  It's a certificate on the server itself that needs updating.  Doing it now.

**Comment by justinclift** [comment]
The certificate on the server has been updated now.  The certificate problems should be gone.

The `Host db4s.dbhub.io not found` error sounds like a DNS problem though.  That one *might* actually be a Snap problem, as Snap seems to cause all kinds of weird and bizarre issues (probably solvable with a bunch of effort).

The easiest workaround is probably to switch to using the AppImage version from here:

https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.13.1

In theory (!), all you need to do is download that and chmod it so it runs.

Maybe try that and see how it all goes? :smile:

**Comment by tomhosker** [comment]
Just tried it again now and everything works. Thank you so much!

**Comment by justinclift** [comment]
You're welcome @tomhosker. :smile:
