### ISSUE TITLE
Login failure from 3rd party cookies

### ISSUE THREAD

**Issue by bfschutt** [sqlitebrowser/dbhub.io#389]
When trying to login to my newly created account, I get the error captured in the attached screenshot. I've changed the settings I know of on my Mac Mini, but it doesn't change the result. Any hints or ideas to resolve this?  Thx, Brian

![Screenshot 2024-11-25 at 5 00 23 PM](https://github.com/user-attachments/assets/3d2c17e7-061d-4767-af05-fc55a2526aa2)

**Comment by justinclift** [comment]
@bfschutt Yeah, it looks like our setup is having issues with Auth0. 😦

As a data point, the whole dbhub.io thing is mostly a concept that didn't work out so we'll be shutting it down in the future (with appropriate notice given).  It's just that I'm super busy at the moment with other stuff, so haven't had time to really think through the details of announcing the upcoming shut down, approriate other bits, etc.

**Comment by bfschutt** [comment]
That's helpful to know! I won't spend anymore time on this then. My attempt to use it was driven by a desire to have a database accessible to several people from multiple devices. I'm such a noob to SQLite that I'm not exactly sure how to create a multi-user remote DB.

**Comment by justinclift** [comment]
No worries at all.  For your use case, https://fly.io might be suitable.  Haven't used it myself personally, but people seem to speak well of it.

@benbjohnson You guys have a free tier yeah?
