### ISSUE TITLE
webui: Should require extra confirmation when deleting a database

### ISSUE THREAD

**Issue by MKleusberg** [sqlitebrowser/dbhub.io#57]
When deleting a database via its setting page it shouldn't delete the database right away. Instead an extra page asking for an extra confirmation would be nice.

**Comment by justinclift** [comment]
Yeah, it's a known problem.  One accidental slip of a mouse click and voila... no database left. :wink:

**Comment by justinclift** [comment]
I first tried to get a nice pop up happening... but failed miserably (something to do with javascript scope and context propagation, and no grokking something about it).  So, the fallback approach is probably to just bounce to a page asking "Are you sure?" before deleting the database.

Should be pretty simple to do.

**Comment by MKleusberg** [comment]
I think that extra 'Are you sure?' page is actually what Github is doing for repositories, too :smiley:

**Comment by justinclift** [comment]
Just added a new "Are you sure" type of page for confirming database deletion with 4a93997254421a60d271b99843ac923f5d2538ed.  It's live on the <a href="https://db4s-beta.dbhub.io">db4s-beta server</a>. :smile:
