### ISSUE TITLE
db4s: Empty root dir when user has no databases

### ISSUE THREAD

**Issue by MKleusberg** [sqlitebrowser/dbhub.io#58]
If a user has no own databases the db4s end point code returns an empty JSON object for the root directory, probably because of [this line](https://github.com/sqlitebrowser/dbhub.io/blob/master/db4s/main.go#L59). As soon as the first database is uploaded the root directory is filled with the user's database as well as other users' public databases.

I think we should support listing the public databases of other users even if you don't have uploaded any databases by yourself.

**Comment by justinclift** [comment]
Good point. :smile:

From looking at that code quickly, the` DB4SDefaultList()` function probably needs a bit of work so it returns the correct list.

**Comment by justinclift** [comment]
Just pushed a fix for this, which I'm pretty sure should be fairly robust.  It's live on the db4s-beta server too. :smile:
