### ISSUE TITLE
webui: Redirect from HTTP to HTTPS

### ISSUE THREAD

**Issue by MKleusberg** [sqlitebrowser/dbhub.io#59]
When trying to open http://db4s-beta.dbhub.io/ (which can easily happen because of the browser's auto completion or similar) you get an error message which might you make wonder if dbhub.io is down. I think it would be better to just redirect any requests to https://db4s-beta.dbhub.io/ instead. This way you more or less enforce the HTTPS protocol but make user errors less likely.

**Comment by justinclift** [comment]
Yeah, it's just due to my being lazy when setting up the server.

It's pretty simple to install nginx, setup the bounce from http → https, and update the firewall rules.

I can get it done later on today. :smile:

**Comment by MKleusberg** [comment]
Cool :smile: No need to hurry though, it really isn't that important. I just wanted to open an issue to put this thought somewhere before it is forgotten :wink:

**Comment by justinclift** [comment]
Just added the redirect. :smile:

**Comment by chrisjlocke** [comment]
If I click the above 1st link, or go to the https site, change it to 'http' and press Enter, Chrome doesn't like it.

![image](https://user-images.githubusercontent.com/7872218/29985240-fe8f13d6-8f55-11e7-933f-e4c13950fcc0.png)

HOWEVER, if i **then** click in the address bar and press Enter, the site loads.  Chrome might just be taking me to the first 'hit' in my address bar though that matches.  Either way, the http->https doesn't seem to be working for me.

**Comment by justinclift** [comment]
Ahhh.  Yeah.  I think I forgot to make Nginx auto-start when the server reboots, and that's what's providing the auto bounce.

Checking now... :smile:

**Comment by justinclift** [comment]
Yep, that was it.  Just manually started it, and set it to automatically start at boot up.

Thanks for pointing it out @chrisjlocke. :smile:

**Comment by chrisjlocke** [comment]
\o/
