### ISSUE TITLE
db4s: Can't always see up to date database list

### ISSUE THREAD

**Issue by MKleusberg** [sqlitebrowser/dbhub.io#64]
I've just pushed a new (private) database to the mtest3 user. It's just a copy of the State of the Sector - Volunteers Chapter.sqlite database that's already on the server. The new database appears in the web view but doesn't always show up in the JSON data for DB4S. If I keep reconnecting it sometimes appears and sometimes it doesn't. Curiously enough the default sort order also correlates to whether the database is shown or not.

Maybe some caching issue?

**Comment by justinclift** [comment]
Yeah, that definitely sounds like a caching issue of some sort.  Thanks, will investigate.

**Comment by justinclift** [comment]
Is this still happening?

Kind of hoping it was due to low thresholds on the database connection pool settings... :wink:

**Comment by MKleusberg** [comment]
It appears to be even worse than before :wink: I don't seem to be able to reproduce #65 because I can't see the database at all.

**Comment by MKleusberg** [comment]
Same as #65.
