### ISSUE TITLE
Add Gravatars

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/dbhub.io#70]
We should probably add support for Gravatars, to make a better, nicer visual experience:

* On the top right next to "Preferences | Home | Log out"
* On the user's page (or should we show a photo there instead?)
* Next to user entries on the commits page

**Comment by chrisjlocke** [comment]
The github way of a custom picture is useful, and would look good when viewing someone elses database.

**Comment by justinclift** [comment]
Agreed.  So far I've avoided having to store user info though, as otherwise we start getting into the territory of PII, data handling, which jurisdiction to have people's data in (eg EU vs US servers), etc.

Thus far we store:

* username
* email address (if given)
* name for display (if given)

And that's it.

We'll definitely need to expand that out & figure out/implement the PII stuff too, but I'm more punting that to later after more of our foundational stuff is working. :smile:

**Comment by chrisjlocke** [comment]
You're linked in with github via Auth0 - can that 'suck down' any images, etc?  Or facebook?  But then dbhub.io would be full of kittens and baby pictures.  Argh.

**Comment by justinclift** [comment]
Ahhh, that's a good idea.  That might indeed be a workable concept.

For users from any particular auth source, we could check if an image is provided by that auth source and use it.  Cool. :smile:

**Comment by justinclift** [comment]
Added reasonable initial support for displaying images/gravatars today.

If Auth0 provides a user pic, it'll use that.  If not, it'll fall back to using a gravatar if the user has give their email address to us.
