### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/dbhub.io#73]
Is the server in flames?

![image](https://user-images.githubusercontent.com/7872218/29274074-6fffb428-80fe-11e7-85a9-04966b469bd5.png)

**Comment by justinclift** [comment]
Damn.  Yeah, the Go process aborted without giving any reason.

I think it might be this:

https://github.com/golang/go/issues/15658

Unresolved crash bug for Golang on FreeBSD.  Ugh.

Might need to deploy on Linux boxes instead, which I really didn't want to do. 😦

**Comment by justinclift** [comment]
For now, I've just restarted the process.  I'll add a monitoring check to Rackspace as well to make sure it tells me at least via email.

Daaaammmmmmmmmmnnit.

**Comment by chrisjlocke** [comment]
> which I really didn't want to do.

More hassle?

**Comment by justinclift** [comment]
Personal dislike of the direction the Linux ecosystem is going.  Personally, if Rackspace supported OpenBSD we'd be running on that. :smile:

**Comment by justinclift** [comment]
Active monitoring of the website is now in Rackspace (every 1 min), so it'll email me if (when 😦) the process next crashes.

Short term... it's completely possible to also put the startup in a loop.  That would probably be sub-second delay too, which is likely good enough for now.

Hmmm... I'll muck around with that today or tomorrow.

**Comment by justinclift** [comment]
This just happened again.  At least alerting via Rackspace email is working. :smile:

I'll put some time into making an auto-launch loop later on, maybe tomorrow, so the outages aren't user visible.  Hmmm, chucking a load balancer in front of things and spinning up an extra server would also work... but seems more effort at this early stages of things. :wink:

**Comment by justinclift** [comment]
Closing this, as our server infrastructure was moved to Linux literally years ago, and it's working fine. :smile:
