### ISSUE TITLE
Better Markdown processor

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/dbhub.io#74]
At present we're rendering Markdown content using [go-commonmark](https://github.com/rhinoman/go-commonmark) which doesn't seem actively developed any more.

We should probably investigate using [Blackfriday](https://github.com/russross/blackfriday) instead, which looks simple to implement too and also supports more useful Markdown extensions (eg tables!).

**Comment by chrisjlocke** [comment]
Is that the Github flavour?

**Comment by justinclift** [comment]
Yep, it seems to support GitHub markdown features too. :smile:

**Comment by justinclift** [comment]
Reading it further, that seems like a definite yes:

&nbsp; &nbsp; https://github.com/russross/blackfriday#other-renderers

**Comment by justinclift** [comment]
Using the "github_flavored_markdown" package directly seems like the right thing:

&nbsp; &nbsp; https://godoc.org/github.com/shurcooL/github_flavored_markdown

It's stripping all bootstrap styling though, which isn't good.  Might need to fork it and adjust it's output for now, and come back to it later for more in-depth investigation.

**Comment by justinclift** [comment]
Yep, needed to fork it and adjust some of it's hard coded settings so it works for us.

Example here, now using markdown tables in it's description:

&nbsp; &nbsp; https://db4s-beta.dbhub.io/nicva/Marine%20Litter%20Survey%20(Keep%20Northern%20Ireland%20Beautiful).sqlite

As a bonus, this also fixes the newline problem [you pointed out](https://github.com/sqlitebrowser/dbhub.io/issues/71#issuecomment-322170306) yesterday. :smile:

**Comment by chrisjlocke** [comment]
Yay!  Well done.  Looks nice.

**Comment by justinclift** [comment]
Thanks. :smile:
