### ISSUE TITLE
link suggestion

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/dbhub.io#78]
Could the database name (not linked at the moment) be a link to settings?

![image](https://user-images.githubusercontent.com/7872218/29279812-f26e7ec8-8110-11e7-99e0-1ebbc31dae8f.png)

This would free up a bit of space, but also make it more 'consistent'.

**Comment by justinclift** [comment]
Hmmm, dunno if it'd make sense.  Guess we can try it out and see how it goes. :smile:

**Comment by chrisjlocke** [comment]
Not a 'deal breaker' - instead, what about in the database list, a cog icon to take you to the settings?

![image](https://user-images.githubusercontent.com/7872218/29281696-f37c7bce-8117-11e7-95dd-60752b380476.png)

**Comment by justinclift** [comment]
Oh, that's a good idea.  Yep, that should be do-able.  Unicode has a gear `⚙` icon already, so we can reuse that.  Probably need to increase the size though.

Alternatively, Font Awesome - which we already use for the About page - has a cog icon:

&nbsp; &nbsp; http://fontawesome.io/icon/cog/

Either way should work. :smile:

**Comment by justinclift** [comment]
Just added the Font Awesome cog to the database list items, live on the beta server:

![database item screenshot](https://user-images.githubusercontent.com/406299/29285830-c84cccbe-8127-11e7-89c7-6f71f16c9885.png)

Yep, it does seem better usability-wise when wanting to go right to the settings page for a database. :smile:

**Comment by justinclift** [comment]
Hmmm, should we add the cog icon to the database display page somewhere too?  eg after the database name or similar

Note -  I have no idea how to get things into the empty left margin space (may not even be possible with our current framework), so to the left of the `user / database` header probably isn't a go-er. 🙄

**Comment by chrisjlocke** [comment]
> Just added the Font Awesome cog to the database list items

Looks nice.  👍

**Comment by justinclift** [comment]
No worries at all, your suggestions are really helping. :smile:
