### ISSUE TITLE
[Newbie Thought] Upload database

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/dbhub.io#80]
When viewing a database, the button that stands out the most is 'upload database', which seems a bit weird, as I'm viewing a database.  If I do upload a database, its not 'connected' to the one I'm viewing, ie, a branch or new commit (unless the filenames match, of course)

From a newbies point of view, this is a little confusing, and I would suggest removing the 'upload database' button from this screen.  From a 'logistics' point of view, I'd go back to my list of databases, and expect a 'upload database' icon there - which it is, top left (ie, asthetically positioned)

Either that, or the 'upload database' should link to the current database, eg, create a new commit, even if the filenames don't match (maybe I'm uploading db1-part1.db, and db1-part2.db is  commit of that database?) Not sure if thats possible / a good idea, etc.  Just viewing the system from a non-programmer! ;)

**Comment by justinclift** [comment]
Ahhh yeah.  That's a good point.

I've often thought that we should do something about having the "Upload database" on the database view page do something with commits.  But, didn't have any further insight.  Getting it to add a new commit to the viewed database sounds like a good way to also address the "make it easier for newbies to understand how to create a new commit" item from yesterday.

Hmmmm, combining that with the outstanding "accept CSV files for upload" could make for a good way to allow users to assemble a database on the website out of several csv files.

None of which is easy right away so it might be better to just nuke that button for now and come back to this?  Or should we leave the button 'as is' for now, and adjust it when we get this done?

**Comment by chrisjlocke** [comment]
Personally I'd hide the button (just comment it instead of nuke it) just to avoid ambiguity... it makes more sense to upload a database from the 'heres your databases' page....  (my view only, of course!)

**Comment by justinclift** [comment]
No worries.  Makes sense to me. :smile:

Just commented it out in 71c8e767c110c76193d29a51fbed3cf7150e60df, and pushed that to the live beta server.

**Comment by justinclift** [comment]
Closing this, as we implemented the improved upload behaviour a while ago.

Now, when a user is looking at a database they'll only see the "Upload database" button if they're logged in + it's a standard database.

Additionally, clicking the upload button on the database page will add a new commit to an existing database (for standard databases, live ones don't have the button).
