### ISSUE TITLE
Better sorting and pagination arrows

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/dbhub.io#84]
It turns out Bootstrap (which we already use) includes better arrows to indicate sorting than what we're presently using for the database view page:

&nbsp; &nbsp; https://getbootstrap.com/docs/3.3/components/

A decent example of them in action is here:

  &nbsp; &nbsp; https://datatables.net/manual/styling/bootstrap (scroll down to "Examples")

We should be able to replace our fairly crap current ones with the better Bootstrap ones.

**Comment by chrisjlocke** [comment]
> Each Bootstrap theme includes all the source and compiled files you'll need, including npm and Gulp based build tools.

You know when you're losing touch with software when you've got to look up all these acronyms and names!  Never heard of npm or Gulp.  Silly sounding names.  Its like creating software called Squidgy.   *continues ranting to himself...*

**Comment by justinclift** [comment]
Yeah, the javascript ecosystem is insane.  We're using Bootstrap 3 (4 is out), AngularJS 1.x (version 4.3.4 is latest), etc.  AngularJS especially seems to be non-optimal, as version 2 is backwards incompatible with version 1.  So, much rewriting will be needed.  And the AngujarJS team somehow decided that making a new major (eg 2 -> 3 -> 4) release *every 6 months* is somehow a good idea.

Very much intending on investigating [Dart](https://www.dartlang.org) instead when it comes time to do said rewrite.  After all, if we rewriting the browser layer, might as well do it in something which has a hope of not needing another major rewrite (again) 6 months later. :wink:

**Comment by justinclift** [comment]
Oh, 'npm` is the "Node package manager".  It's a command line utility for people who use Javascript/NodeJS and want to install/manage local javascript packages.  It's similar to other command line utilities that do the same thing for other languages (Pip for Python, etc).

**Comment by justinclift** [comment]
Changed out the sorting arrows in 7d16f4731a09627fae82c79f89da4dd30c33eba9. :smile:

Haven't looked into pagination stuff yet, and probably won't today.

**Comment by justinclift** [comment]
Closing this, as we reworked the pagination buttons last week.

Heh, bit of a time lag with this one. :wink:
