### ISSUE TITLE
Uploads from DB4S aren't really working

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/dbhub.io#87]
Uploads from DB4S to DBHub.io aren't really working properly. 😦 

For the db4s-beta server, if the database size is very small (~50kB), then the upload can sometimes work.  Anything bigger than that though and it just hangs on the DB4S side... the server just seems to be waiting for the rest of the input to arrive.

On my local development system, the same thing happens but at a larger file size (~500kB).

Not really sure what could be causing this.  Dumping the request headers for info purposes shows one potential weirdness when comparing it to curl uploading of the same database.  Note, curl uploads work 100% of the time without error .

#### Headers sent by DB4S

```
Mime-Version	[1.0]
User-Agent	[sqlitebrowser 3.9.200]
Content-Type	[multipart/form-data; boundary="boundary_.oOo._MTY0NjIxOTcxMQ==MzgzOTkwOTc1MTMyNjk3MzI1NA=="]
Content-Length	[557607]
Connection	[Keep-Alive]
Accept-Encoding	[gzip, deflate]
Accept-Language	[en-US,*]
```

#### Headers sent by curl
```
User-Agent	[curl/7.51.0]
Accept	[*/*]
Content-Length	[557777]
Expect	[100-continue]
Content-Type	[multipart/form-data; boundary=------------------------2111738db80eaa40]
```

In the above output the "Content-Length" field is different between the two.  The DB4S one is the exact size of the test database I'm uploading, whereas the curl output is larger.  At a guess, the curl Content-Length is including the either the request headers too, or perhaps the data is being encoded differently on the way (unsure yet).

Not sure if that's really the cause of the problem though.  If it was, I'd expect uploads from DB4S to never work, not just sometimes.

Still investigating.

**Comment by justinclift** [comment]
Hmmmm, I wonder if we should just disable uploading in the DB4S remote dock for now, and get it working after the 3.10.0 release?

@karim @chrisjlocke Thoughts?

**Comment by chrisjlocke** [comment]
Is the [content-length] being created by DB4S?  Is there any way of confirming that figure, either by DB4S or by the server?  (ie, "you said 557607 but I only got 557601, so I'll wait for the rest....") ?  Or is it just a 'rough approximation' and it doesn't go on that?

DB4S seems more 'strict' in its headers - Mime-Version, Connection, Accept-Encoding and Accept-Language.  Can they be temporarily removed to see if one of those is causing an issue?  (just trying to make it match the Curl one as much as possible...)

**Comment by justinclift** [comment]
Yeah, I've just been reading through the Qt5 docs in detail.  It doesn't seem to have that many knobs available for turning.  The content length figure there is generated by DB4S.

Interestingly, after getting fed up and trying out near-random things in the DB4S source... I've found a way to get uploads to work 100% of the time for me ~500kB ones.  By commenting out the [`prepareProgressDialog()`](https://github.com/sqlitebrowser/sqlitebrowser/blob/503a329b706e377c7cb98085725abe6c90a6952d/src/RemoteDatabase.cpp#L443) line.

Unfortunately, DB4S crashes immediately afterwards too.  So, not really a win there, but it's potentially useful info for figuring out what's wrong.

It's been so long since I did any C++/Qt stuff though, that I'm really struggling. 😦 

Anyway I'm now attempting to attach a debugger to see if I can catch what's causing the crash.

**Comment by justinclift** [comment]
Aha, this line is causing the crash.

Commenting it out, with `prepareProgressDialog()` (as above) also commented out... and the upload seems to work every time.

I'll see if I can figure out what's going on... :smile:

**Comment by justinclift** [comment]
Ok, the crash is definitely caused by this particular line: https://github.com/sqlitebrowser/sqlitebrowser/blob/503a329b706e377c7cb98085725abe6c90a6952d/src/RemoteDatabase.cpp#L247.

The one pointed out before seems to make things worse, so removing them both helps.

The progress dialog itself though now runs through to completion most of the time (90%) with small files (<1MB) against the db4s-beta server.  But the progress dialog itself still hangs a lot when uploading bigger ones.

... still experimenting.

**Comment by justinclift** [comment]
Worked out the cause and a good fix for this yesterday evening.  It turns out having a dialog declared as Modal is pretty much incompatible with kicking off the processEvents() call in Qt.

So, disabled that in https://github.com/sqlitebrowser/sqlitebrowser/commit/0c20582edbe0a4bbc9551d39680a7040f1bf402a, then proceeded to do wider testing just to make super sure.

With that fix in place, uploading now works 100% of the time (for me) from Linux (Fedora 25), OSX (10.11.x), and Win 7 x64.  File sizes from ~50kB through to 1/2 GB, all upload perfectly.

So, calling this one "done" now. :smile:
