### ISSUE TITLE
Error when parsing full name value (with number)

### ISSUE THREAD

**Issue by mercury233** [sqlitebrowser/dbhub.io#91]
![image](https://user-images.githubusercontent.com/13391795/29865294-c21154aa-8da7-11e7-9a3f-54d3435a90ac.png)
then
![image](https://user-images.githubusercontent.com/13391795/29865308-ce383b18-8da7-11e7-90b8-10b8cdba04e7.png)

I've found that full name can't include number, so it should be validated in front end too.

**Comment by justinclift** [comment]
Ahhhh, thanks @mercury233.  I just emailed you about that, after seeing the error popping up on the system console about the failure.

I've pushed a patch to allow numbers in that field (cb063ce814f31e34cbca127a82886f664c9b714c), so it should work now.

**Comment by mercury233** [comment]
Thank you!

**Comment by justinclift** [comment]
You're welcome. :smile:

And yeah, the front end code should validate to match the back end code.  I haven't yet looked into proper validation there, and probably won't for a while as my focus is now on getting "merge requests" working which (I think) is higher priority.

But, it that validation bit will get done at some point. :smile:

**Comment by justinclift** [comment]
Ugh, it looks like you're being affected by a different bug I accidentally introduced a few days ago too.

Hang on, I should get that fixed shortly as well.

... we definitely also need to add better automated testing to this stuff. :wink:

**Comment by justinclift** [comment]
Ok, this is going to take a bit longer than I thought.  Um... I'll have it fixed in a few hours.  Your database uploads worked, but the page to display things is reading table names incorrectly.

Ugh.  Sorry.

**Comment by justinclift** [comment]
It turned out the fix was easy, I just needed to look in the right spot.  Now fixed. :smile:

**Comment by chrisjlocke** [comment]
*@justinclift happily talks to himself...*

**Comment by justinclift** [comment]
> @justinclift happily talks to himself...

Probably not the first time.  😁
