### ISSUE TITLE
Request: Add "View" view

### ISSUE THREAD

**Issue by mercury233** [sqlitebrowser/dbhub.io#93]
Now [my database](https://db4s-beta.dbhub.io/mercury233/pre-release.cdb) is hard to read in page because it have too much columns.
![image](https://user-images.githubusercontent.com/13391795/29867368-eb2ccb16-8dad-11e7-82b1-150c0dfda7f0.png)

Can we use the "[View](https://sqlite.org/lang_createview.html)" feature of sqlite to make it easier to read?
![image](https://user-images.githubusercontent.com/13391795/29867380-f97d1afe-8dad-11e7-8f1e-a91ab4b77a4a.png)

**Comment by justinclift** [comment]
Ahhh, that's a good idea.

If you're ok to email me or upload a database with an example view, I'll take some time today to try and get that working. :smile:

**Comment by mercury233** [comment]
https://db4s-beta.dbhub.io/mercury233/pre-release.cdb?branch=master&commit=da7d5c38f724aea786ce3cc494f3305644c03c714ad6ca8f6537b7d6150e812c
is uploaded

**Comment by justinclift** [comment]
Thanks, got it. :smile:

**Comment by justinclift** [comment]
@mercury233 This should work now. :smile:

&nbsp; &nbsp; https://db4s-beta.dbhub.io/mercury233/pre-release.cdb

**Comment by justinclift** [comment]
Note - it's only a first attempt (in ba3054273c7a573cebffa35fcaccc89569d9cd24), but it should function ok.  Most of the wording in the UI that says "Table" or "Tables" will probably need changing to be "Table/View" or "Tables/Views"... but that can come later. :smile:

**Comment by mercury233** [comment]
I've updated the database, but the view don't update when i refresh the page, unless I select the view in list again.
![image](https://user-images.githubusercontent.com/13391795/29869276-eb926e24-8db4-11e7-8730-79fb0e0fb503.png)
![image](https://user-images.githubusercontent.com/13391795/29869288-f784abfc-8db4-11e7-84f3-6de9b865995b.png)

BTW, I think there should be an option to make texts render as raw text, so the line breaks will work.
_And I'm glad to see the XSS filter works well_

**Comment by justinclift** [comment]
> I've updated the database, but the view don't update when i refresh the page, unless I select the view in list again.

Oh.  That's means there's a bug in the way we're pulling data out of cache.  I can disable the cache for now to "make it work", but I'll need to investigate in more depth to find out a proper solution.  I'll get that disabling done in a few minutes.

Also, I changed the display so it doesn't force all of the columns to the same with.  Now `desc` should take up the most room on the page.  I'm not sure if that's better or not... if you don't like it, let me know and I'll change it back. :smile:

**Comment by justinclift** [comment]
Ahhh... actually I know what the problem is.  At the moment when a database is uploaded using DB4S, memcache doesn't get told about it so uses old data.

Working on a fix now. :smile:

**Comment by mercury233** [comment]
It looks much better now, thanks!
_what about custom css_

**Comment by justinclift** [comment]
Custom CSS?

**Comment by mercury233** [comment]
Yes, so I can decide how wide the second column should be, and more.

**Comment by justinclift** [comment]
Hmmm, it's a good suggestion, but I think it would be difficult to implement at the moment.

We'd probably need to add some kind of form or field or "something" :wink: to the settings page, which lets a person pick settings for displaying their tables/views.  That's probably a few days worth of development time.

Unless I am making it more complicated than it needs to be?  If there's a simpler way, I'm open to suggestions. :smile:

**Comment by justinclift** [comment]
@mercury233 Sort and paging now work for views too.

**Comment by mercury233** [comment]
```css
.table>thead>tr>th:nth-child(2) {
    width: 20em;
}
.table>tbody>tr>td:nth-child(3) {
    font-size: 12px;
}
```
I guess one field to post CSS like this, and one class for the main table, should be enough for me.

**Comment by mercury233** [comment]
Anyway, custom css can change the page entirely, and will have much security problem, so it is just a idea...

**Comment by justinclift** [comment]
Ahhh.  That's probably do-able, but not today. :smile:

You're right we need to be careful with it.  The code we use for stripping out potential XSS (and similar) is "[bluemonday](github.com/microcosm-cc/bluemonday)".  We use it here, and provide it a few [slightly custom rules](https://github.com/justinclift/github_flavored_markdown/blob/master/main.go#L94-L99) so it doesn't strip out AngularJS tags from tables.

At a guess, we'll need to work out what "acceptable" custom CSS should be, then update our bluemonday configuration to allow that too.  In theory that would work without opening up security problems. :smile:

**Comment by chrisjlocke** [comment]
Isn't that what codeMonkey or some development tools in a browswer can do?  Adjust the CSS 'on the fly'?

**Comment by justinclift** [comment]
Sure, but this is a different thing.  @mercury233's idea is to have some kind of thing in the settings page for a database which lets custom css be defined, and that gets sent out with the rest of the page when people view a database.  Thus customised looking views.

The concept sounds both useful and decent.  Implementing it could be a bit tricky, as we need to make sure that if people add dodgy custom CSS (eg for cross site scripting or whatever), that it doesn't work.

That means we need the server side part to recognise dodgy CSS and barf on it.  Or at least have a white list of acceptable CSS and only accept that.  Otherwise we end up serving up potentially malicious code... (!)

Browser side development tools don't really fit into that particular equation, apart from the person figuring out what css they want to include in the first place.  And well... anyone that wants custom CSS (at first) will need to be familiar with it already. :smile:

**Comment by justinclift** [comment]
> BTW, I think there should be an option to make texts render as raw text, so the line breaks will work.

Ahhh, I missed that.  I'll investigate this today too.  It should be possible. :smile:

**Comment by justinclift** [comment]
@mercury233 Line breaks should be displayed ok now. :smile:

**Comment by justinclift** [comment]
Closing this, as view support was added ages ago. :smile:
