### ISSUE TITLE
Auth0 'testing' text

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/dbhub.io#96]
Just a note that 'Testing 1' is used on the GitHub sign in page for logging in.

![image](https://user-images.githubusercontent.com/7872218/29917537-2bcac0c4-8e3a-11e7-837c-85e817cbcba1.png)

And is your smiling face going to stay there? ;)
I appreciate its going to change at some point, but didn't know if 'DBHub.io Beta Server' was more descriptive, now its 'in the wild' more....

**Comment by justinclift** [comment]
Ahhh... yeah... we'll probably need to configure it to use the sqlitebrowser.org account instead.

**Comment by MKleusberg** [comment]
I guess we can close this now that #130 is closed?

**Comment by chrisjlocke** [comment]
Good point ... seems every issue I open is related to logging in!! 😄
