### ISSUE TITLE
db4s: Check commit id when pushing databases

### ISSUE THREAD

**Issue by MKleusberg** [sqlitebrowser/dbhub.io#99]
When pushing a new database version I'd like to be able to specify the last commit id that I know of and have the dbhub code check it.

The idea is to have a new multipart form field, maybe called "last_commit_id" or so, in which I can pass my last known commit id. This can be understood as "here's my new version that I want to commit, and it's based on that last commit". The dbhub.io code should then check that it's the latest commit for this database and branch. If it is, it should just add the new commit. If it isn't it should (probably) do nothing and return with an error message. This way we can make sure that commits are always consecutive and it's impossible to overwrite commits by accidence.

Example:
I have a database with commits 1, 2, and 3. Now I check out the database and get commit 3 which I edit. From some other device or by using the web interface I push a new commit, commit 4. Then, back in DB4S, I push my changes and currently it will create a new commit, commit 5, but that commit doesn't include the changes from commit 4. With the new form field, this confusion and error source could be avoided and the user would know that he's got to do some manual merging.

Also, this field should be optional. If it's not set, we'll just skip the check. This way I can implement a force push feature in DB4S.

Also note that this can't be done client side in DB4S. Of course I could download the version history and check for myself but that would be 1) more complicated than doing it server side (I think) and 2) more error prone because it's not an atomic operation and never can be (after I've downloaded the version history and while I'm doing the checking somebody else might push a new commit).

**Comment by justinclift** [comment]
> The dbhub.io code should then check that it's the latest commit for this database and branch.

Ahhh yep, definitely makes sense.  Git style branch collision detection.  Oh that note, I'll add some kind of querying capability to the DB4S end point bits soon, so DB4S can ask "what branches exist for this database?" then do intelligent things with it.

Not sure if that needs to be done first (it should be pretty easy to implement server side), but it would allow for people to choose non-master branches when uploading.

**Comment by MKleusberg** [comment]
> Not sure if that needs to be done first (it should be pretty easy to implement server side), but it would allow for people to choose non-master branches when uploading.

I don't think it needs to be done first. But feel free to implement it first if you feel like it :wink: If it works similar to getting the licence list, I can easily add it to the push dialog.

**Comment by justinclift** [comment]
No worries.  I'll probably get this done in a few hours.  Still waking up atm and pre-coffee. :smile:

**Comment by justinclift** [comment]
k, just added a `/branch/list` URL to the DB4S end point (live on the db4s-beta server).  It takes 3 GET parameters.

* username
* folder
* dbname

(So far) it returns 4 pieces of info per branch:

* name of the branch
* commit ID of the head commit for the branch
* number of commits the branch has
* the description for the branch

With the branch description bit, markdown is supported in the field for display (eg in the webUI), but this is just the plain text version.  It's super easy to also return the HTML rendered version in an extra field if useful. :smile:

Examples:

*Btw, note the URL encoding (eg of spaces) in the GET parameters*

```
$ curl -kE ~/my.cert.pem -D headers.out -G -d "username=justinclift" \
    -d "folder=/" -d "dbname=DB4S%20download%20stats.sqlite" \
    https://db4s-beta.dbhub.io:5550/branch/list
{
  "master": {
    "commit": "19328348db45c3cf290132b6f35b9fd6e9d6c23f12292e6b07a8698a5f97146b",
    "commit_count": 7,
    "description": "### The main branch.\n\nWe don't really have a need for multiple branches with DB4S download stats. :)"
  }
}
```

```
$ curl -kE ~/my.cert.pem -D headers.out -G -d "username=justinclift" \
    -d "folder=/" -d "dbname=backblaze-drive_stats.db" '
    https://db4s-beta.dbhub.io:5550/branch/list
{
  "dev branch": {
    "commit": "bd20928c99826ad56430ff517465bac7d179c09381309dd11256f696e03aebf0",
    "commit_count": 1,
    "description": "### A simple dev branch\n\nTesting stuff out in here.  May or may not turn out to be useful. :)"
  },
  "master": {
    "commit": "5e9fe0d80b7e85bb3b027499c336b4f4b8c071a5a55075aab06adbab50c083c9",
    "commit_count": 2,
    "description": ""
  }
}
```

**Comment by justinclift** [comment]
Just added working collision detection and support to the DB4S end point, and updated the db4s-beta server with it.

The DB4S end point now **requires** a commit ID to be provided with uploads for databases that already exist.  It's a breaking change (!), so people using DB4S 3.10.0 will only be able to successfully do the first upload.  Subsequent uploads will complain about an upgrade being required.

Shouldn't be much of an issue, as there are very few (less than 10) non-DB4S-developers pushing to the beta server using DB4s with any kind of regularity. :wink:

An example `curl` line to emulate the DB4S call:

```
  $ curl -kE ~/my.cert.pem -D headers.out -F file=@someupload.sqlite \
      -F "public=true" -F "commitmsg=stuff" \
      -F "sourceurl=https://example.org" -F "licence=CC0" \
      -F "branch=master" \
      -F "commit=51d494f2c5eb6734ddaa204eccb9597b426091c79c951924ac83c72038f22b55" \
      -F "force=true" \
      https://db4s-beta.dbhub.io:5550/someuser
```

The `force=true` field is only needed when rewriting commit history.  Without it, the end point will return a collision error.  Testing on my local dev server quite a lot over the last few hours, things seem ok.  Initial testing on the db4s-beta server also seems ok.

**Comment by MKleusberg** [comment]
DB4S is now sending the commit id as requested. I've also added a force push check box to the push dialog. Seems to work fine for me at least, no more Upgrade required messages. Can you double check though? Note that using different branches probably doesn't work as expected yet, so better not to try that until later :smile:

**Comment by MKleusberg** [comment]
Closing this because it's a very old issue and seems to be solved :smile:
